// mobiscroll-demos-vue/src/demos/eventcalendar/calendar-view/colored-cell-background/colored-cell-background.vue
<script setup>
import { getJson, MbscEventcalendar, setOptions /* localeImport */ } from '@mobiscroll/vue'
import { onMounted, ref } from 'vue'
import { dyndatetime } from '../../../../dyndatetime'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([])

const myColors = ref([
  {
    start: dyndatetime('y,m,0'),
    end: dyndatetime('y,m,1'),
    background: '#fde4c880'
  },
  {
    start: dyndatetime('y,m,17'),
    end: dyndatetime('y,m,20'),
    background: '#d5f1ea80'
  },
  {
    date: dyndatetime('y,m,29'),
    background: '#ffdbdb80'
  },
  {
    date: dyndatetime('y,m+1,3'),
    background: '#fbedd080'
  },
  {
    date: dyndatetime('y,m+1,10'),
    background: '#fbedd080'
  },
  {
    background: '#d6e81e1a',
    recurring: {
      repeat: 'monthly',
      day: -1
    }
  }
])

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <!-- dragOptions -->
  <MbscEventcalendar :data="myEvents" :colors="myColors" />
</template>

// react/src/demos/eventcalendar/eventcalendar/colored-cell-background/colored-cell-background.jsx
import React from 'react';
import { Eventcalendar, getJson, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

const myColors = [
  {
    start: 'dyndatetime(y,m,0)',
    end: 'dyndatetime(y,m,1)',
    background: '#fde4c880',
  },
  {
    start: 'dyndatetime(y,m,17)',
    end: 'dyndatetime(y,m,20)',
    background: '#d5f1ea80',
  },
  {
    date: 'dyndatetime(y,m,29)',
    background: '#ffdbdb80',
  },
  {
    date: 'dyndatetime(y,m+1,3)',
    background: '#fbedd080',
  },
  {
    date: 'dyndatetime(y,m+1,10)',
    background: '#fbedd080',
  },
  {
    background: '#d6e81e1a',
    recurring: {
      repeat: 'monthly',
      day: -1,
    },
  },
];

function App() {
  const [myEvents, setEvents] = React.useState([]);

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  return <Eventcalendar data={myEvents} colors={myColors} />;
}

export default App;
