// react-ts/src/demos/range/range/min-max-restrictions/min-max-restrictions.tsx
import { Datepicker, setOptions /* localeImport */ } from '@mobiscroll/react';
import React from 'react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => (
  <div>
    <Datepicker controls={['calendar']} select="range" display="inline" min="1920-01-01" max="2050-01-01" />

    <Datepicker controls={['calendar', 'time']} select="range" display="inline" min="2000-01-01T12:00" max="2050-01-01T12:00" />
  </div>
);
export default App;

// vue/src/demos/range/range/min-max-restrictions/min-max-restrictions.vue
<script setup>
import { MbscDatepicker, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscDatepicker
    :controls="['calendar']"
    select="range"
    display="inline"
    min="1920-01-01"
    max="2050-01-01"
  />
  <MbscDatepicker
    :controls="['calendar', 'time']"
    select="range"
    display="inline"
    min="2000-01-01T12:00"
    max="2050-01-01T12:00"
  />
</template>
