// vue/src/demos/datetime/datetime/setting-the-picker-timezone/setting-the-picker-timezone.vue
<script setup>
import { ref } from 'vue'
import { MbscDatepicker, momentTimezone, setOptions /* localeImport */ } from '@mobiscroll/vue'
import * as moment from 'moment-timezone'

momentTimezone.moment = moment

setOptions({
  // locale,
  // theme
})

const selected = ref()
</script>

<template>
  <MbscDatepicker
    :controls="['datetime']"
    :timezonePlugin="momentTimezone"
    v-model="selected"
    dataTimezone="utc"
    displayTimezone="local"
    label="Select Date &amp; Time in Display Timezone"
    inputStyle="outline"
    labelStyle="stacked"
  />
  <div class="mbsc-padding">
    <p v-if="selected">
      Selected date is returned in Data Timezone<br />
      <code>{{ selected }}</code>
    </p>
  </div>
</template>

// mobiscroll-demos-react-ts/src/demos/datepicker/datetime/setting-the-picker-timezone/setting-the-picker-timezone.tsx
import { Datepicker, MbscDatepickerChangeEvent, momentTimezone, setOptions /* localeImport */ } from '@mobiscroll/react';
import moment from 'moment-timezone';
import { FC, useCallback, useState } from 'react';

// Setup Mobiscroll Timezone plugin with Moment
momentTimezone.moment = moment;

setOptions({
  // localeJs,
  // themeJs
});

const App: FC = () => {
  const [selected, setSelected] = useState<string | null>(null);

  const handleChange = useCallback((ev: MbscDatepickerChangeEvent) => {
    setSelected(ev.value as string);
  }, []);

  return (
    <Datepicker
      controls={['datetime']}
      value={selected}
      onChange={handleChange}
      dataTimezone="utc"
      displayTimezone="local"
      inputStyle="outline"
      label="Pick date & time"
      labelStyle="stacked"
      timezonePlugin={momentTimezone}
    />
  );
};

export default App;
