// mobiscroll-demos-vue/src/demos/eventcalendar/timeline/setting-row-height/setting-row-height.vue
<script setup>
import { MbscEventcalendar, setOptions /* localeImport */ } from '@mobiscroll/vue'
import { dyndatetime } from '../../../../dyndatetime'

setOptions({
  // locale,
  // theme
})

const myEvents = [
  {
    start: dyndatetime('y,m,2'),
    end: dyndatetime('y,m,5'),
    title: 'Event 1',
    resource: 'res1'
  },
  {
    start: dyndatetime('y,m,9'),
    end: dyndatetime('y,m,15'),
    title: 'Event 2',
    resource: 'res1'
  },
  {
    start: dyndatetime('y,m,5'),
    end: dyndatetime('y,m,9'),
    title: 'Event 3',
    resource: 'res2'
  },
  {
    start: dyndatetime('y,m,8'),
    end: dyndatetime('y,m,13'),
    title: 'Event 4',
    resource: 'res3'
  },
  {
    start: dyndatetime('y,m,7'),
    end: dyndatetime('y,m,12'),
    title: 'Event 5',
    resource: 'res3'
  },
  {
    start: dyndatetime('y,m,3'),
    end: dyndatetime('y,m,10'),
    title: 'Event 6',
    resource: 'res4'
  },
  {
    start: dyndatetime('y,m,15'),
    end: dyndatetime('y,m,23'),
    title: 'Event 7',
    resource: 'res4'
  },
  {
    start: dyndatetime('y,m,12'),
    end: dyndatetime('y,m,17'),
    title: 'Event 8',
    resource: 'res5'
  },
  {
    start: dyndatetime('y,m,8'),
    end: dyndatetime('y,m,13'),
    title: 'Event 9',
    resource: 'res6'
  },
  {
    start: dyndatetime('y,m,20'),
    end: dyndatetime('y,m,27'),
    title: 'Event 10',
    resource: 'res7'
  },
  {
    start: dyndatetime('y,m,6'),
    end: dyndatetime('y,m,12'),
    title: 'Event 11',
    resource: 'res8'
  },
  {
    start: dyndatetime('y,m,18'),
    end: dyndatetime('y,m,25'),
    title: 'Event 12',
    resource: 'res8'
  }
]

const myResources = [
  {
    id: 'gro1',
    name: 'Team 1',
    color: '#ff1717',
    eventCreation: false,
    children: [
      {
        id: 'res1',
        name: 'Ryan',
        color: '#1dab2f',
        title: 'Cloud System Engineer',
        img: 'https://img.mobiscroll.com/demos/m1.png'
      },
      {
        id: 'res2',
        name: 'Kate',
        color: '#e20000',
        title: 'Help Desk Specialist',
        img: 'https://img.mobiscroll.com/demos/f1.png'
      },
      {
        id: 'res3',
        name: 'John',
        color: '#4981d6',
        title: 'Application Developer',
        img: 'https://img.mobiscroll.com/demos/m2.png'
      }
    ]
  },
  {
    id: 'gro2',
    name: 'Team 2',
    eventCreation: false,
    children: [
      {
        id: 'res4',
        name: 'Mark',
        color: '#f7961e',
        title: 'Data Quality Manager',
        img: 'https://img.mobiscroll.com/demos/m3.png'
      },
      {
        id: 'res5',
        name: 'Sharon',
        color: '#34c8e0',
        title: 'Network Administrator',
        img: 'https://img.mobiscroll.com/demos/f2.png'
      }
    ]
  },
  {
    id: 'gro3',
    name: 'Team 3',
    color: '#af0000',
    eventCreation: false,
    children: [
      {
        id: 'res6',
        name: 'Emma',
        color: '#843100',
        title: 'Client Services Manager',
        img: 'https://img.mobiscroll.com/demos/f3.png'
      },
      {
        id: 'res7',
        name: 'Ashley',
        color: '#4caf00',
        title: 'Instructional Designer',
        img: 'https://img.mobiscroll.com/demos/f4.png'
      },
      {
        id: 'res8',
        name: 'Derek',
        color: '#7056ff',
        title: 'Architectural Engineer',
        img: 'https://img.mobiscroll.com/demos/m4.png'
      }
    ]
  }
]

const myView = {
  timeline: {
    type: 'month'
  }
}
</script>

<template>
  <MbscEventcalendar
    className="md-timeline-row-height"
    :clickToCreate="true"
    :dragToCreate="true"
    :dragToMove="true"
    :dragToResize="true"
    :view="myView"
    :data="myEvents"
    :resources="myResources"
  >
    <template #resource="resource">
      <div class="md-timeline-row-height-cont" v-if="!resource.children">
        <div class="md-timeline-row-height-name">{{ resource.name }}</div>
        <div class="md-timeline-row-height-title">{{ resource.title }}</div>
        <img class="md-timeline-row-height-avatar" :src="resource.img" />
      </div>
      <div v-if="resource.children">{{ resource.name }}</div>
    </template>
  </MbscEventcalendar>
</template>

<style>
.md-timeline-row-height .mbsc-timeline-row {
  height: 78px;
}

.md-timeline-row-height .mbsc-timeline-parent {
  height: 32px;
}

.md-timeline-row-height .mbsc-timeline-row-gutter {
  height: 6px;
}

.md-timeline-row-height-cont {
  position: relative;
  padding-left: 50px;
}

.md-timeline-row-height-avatar {
  position: absolute;
  max-height: 50px;
  max-width: 50px;
  top: 30px;
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  left: 10px;
}

.md-timeline-row-height-name {
  font-size: 16px;
}

.md-timeline-row-height-title {
  font-size: 13px;
  margin-top: 5px;
}
</style>

// react-ts/src/demos/eventcalendar/timeline/setting-row-height/setting-row-height.tsx
import React from 'react';
import { Eventcalendar, MbscEventcalendarView, MbscCalendarEvent, MbscResource, setOptions /* localeImport */ } from '@mobiscroll/react';
import './setting-row-height.css';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => {
  const view = React.useMemo<MbscEventcalendarView>(() => {
    return {
      timeline: {
        type: 'month',
      },
    };
  }, []);

  const myEvents = React.useMemo<MbscCalendarEvent[]>(() => {
    return [
      {
        start: 'dyndatetime(y,m,2)',
        end: 'dyndatetime(y,m,5)',
        title: 'Event 1',
        resource: 'res1',
      },
      {
        start: 'dyndatetime(y,m,9)',
        end: 'dyndatetime(y,m,15)',
        title: 'Event 2',
        resource: 'res1',
      },
      {
        start: 'dyndatetime(y,m,5)',
        end: 'dyndatetime(y,m,9)',
        title: 'Event 3',
        resource: 'res2',
      },
      {
        start: 'dyndatetime(y,m,8)',
        end: 'dyndatetime(y,m,13)',
        title: 'Event 4',
        resource: 'res3',
      },
      {
        start: 'dyndatetime(y,m,7)',
        end: 'dyndatetime(y,m,12)',
        title: 'Event 5',
        resource: 'res3',
      },
      {
        start: 'dyndatetime(y,m,3)',
        end: 'dyndatetime(y,m,10)',
        title: 'Event 6',
        resource: 'res4',
      },
      {
        start: 'dyndatetime(y,m,15)',
        end: 'dyndatetime(y,m,23)',
        title: 'Event 7',
        resource: 'res4',
      },
      {
        start: 'dyndatetime(y,m,12)',
        end: 'dyndatetime(y,m,17)',
        title: 'Event 8',
        resource: 'res5',
      },
      {
        start: 'dyndatetime(y,m,8)',
        end: 'dyndatetime(y,m,13)',
        title: 'Event 9',
        resource: 'res6',
      },
      {
        start: 'dyndatetime(y,m,20)',
        end: 'dyndatetime(y,m,27)',
        title: 'Event 10',
        resource: 'res7',
      },
      {
        start: 'dyndatetime(y,m,6)',
        end: 'dyndatetime(y,m,12)',
        title: 'Event 11',
        resource: 'res8',
      },
      {
        start: 'dyndatetime(y,m,18)',
        end: 'dyndatetime(y,m,25)',
        title: 'Event 12',
        resource: 'res8',
      },
    ];
  }, []);

  const myResources = React.useMemo<MbscResource[]>(() => {
    return [
      {
        id: 'gro1',
        name: 'Team 1',
        color: '#ff1717',
        eventCreation: false,
        children: [
          {
            id: 'res1',
            name: 'Ryan',
            color: '#1dab2f',
            title: 'Cloud System Engineer',
            img: 'https://img.mobiscroll.com/demos/m1.png',
          },
          {
            id: 'res2',
            name: 'Kate',
            color: '#e20000',
            title: 'Help Desk Specialist',
            img: 'https://img.mobiscroll.com/demos/f1.png',
          },
          {
            id: 'res3',
            name: 'John',
            color: '#4981d6',
            title: 'Application Developer',
            img: 'https://img.mobiscroll.com/demos/m2.png',
          },
        ],
      },
      {
        id: 'gro2',
        name: 'Team 2',
        eventCreation: false,
        children: [
          {
            id: 'res4',
            name: 'Mark',
            color: '#f7961e',
            title: 'Data Quality Manager',
            img: 'https://img.mobiscroll.com/demos/m3.png',
          },
          {
            id: 'res5',
            name: 'Sharon',
            color: '#34c8e0',
            title: 'Network Administrator',
            img: 'https://img.mobiscroll.com/demos/f2.png',
          },
        ],
      },
      {
        id: 'gro3',
        name: 'Team 3',
        color: '#af0000',
        eventCreation: false,
        children: [
          {
            id: 'res6',
            name: 'Emma',
            color: '#843100',
            title: 'Client Services Manager',
            img: 'https://img.mobiscroll.com/demos/f3.png',
          },
          {
            id: 'res7',
            name: 'Ashley',
            color: '#4caf00',
            title: 'Instructional Designer',
            img: 'https://img.mobiscroll.com/demos/f4.png',
          },
          {
            id: 'res8',
            name: 'Derek',
            color: '#7056ff',
            title: 'Architectural Engineer',
            img: 'https://img.mobiscroll.com/demos/m4.png',
          },
        ],
      },
    ];
  }, []);

  const renderMyResource = (resource: MbscResource) => {
    return (
      <div>
        {resource.children ? (
          <div>{resource.name}</div>
        ) : (
          <div className="md-timeline-row-height-cont">
            <div className="md-timeline-row-height-name">{resource.name}</div>
            <div className="md-timeline-row-height-title">{resource.title}</div>
            <img className="md-timeline-row-height-avatar" src={resource.img} alt="Avatar" />
          </div>
        )}
      </div>
    );
  };

  return (
    <Eventcalendar
      className="md-timeline-row-height"
      view={view}
      data={myEvents}
      resources={myResources}
      renderResource={renderMyResource}
      clickToCreate={true}
      dragToCreate={true}
      dragToMove={true}
      dragToResize={true}
    />
  );
};
export default App;
