// vue/src/demos/calendar/calendar/multiple-months/multiple-months.vue
<script setup>
import { MbscDatepicker, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" :pages="1" />
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" :pages="2" />
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" :pages="3" />
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" pages="auto" />
</template>

// react/src/demos/calendar/calendar/multiple-months/multiple-months.jsx
import React from 'react';
import { Datepicker, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  return (
    <div>
      <Datepicker controls={['calendar']} display="inline" calendarType="month" pages={1} />
      <Datepicker controls={['calendar']} display="inline" calendarType="month" pages={2} />
      <Datepicker controls={['calendar']} display="inline" calendarType="month" pages={3} />
      <Datepicker controls={['calendar']} display="inline" calendarType="month" pages="auto" />
    </div>
  );
}

export default App;
