// react/src/demos/eventcalendar/scheduler/load-events-from-remote-api/load-events-from-remote-api.jsx
import React from 'react';
import { Eventcalendar, getJson /* localeImport */ } from '@mobiscroll/react';

function App() {
  const [myEvents, setEvents] = React.useState([]);

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  const view = React.useMemo(() => {
    return {
      calendar: { type: 'week' },
      schedule: { type: 'day' },
    };
  }, []);

  return (
    <Eventcalendar
      // theme
      // locale
      // drag
      data={myEvents}
      view={view}
    />
  );
}

export default App;

// vue/src/demos/eventcalendar/scheduler/load-events-from-remote-api/load-events-from-remote-api.vue
<script setup>
import { ref, onMounted } from 'vue'
import { MbscEventcalendar, setOptions, getJson /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([])

const myView = {
  calendar: { type: 'week' },
  schedule: { type: 'day' }
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template><MbscEventcalendar :drag="drag" :view="myView" :data="myEvents" /></template>
