// mobiscroll-demos-react/src/demos/eventcalendar/calendar-view/searching-events-in-popup/searching-events-in-popup.jsx
import {
  CalendarNav,
  CalendarNext,
  CalendarPrev,
  CalendarToday,
  Eventcalendar,
  formatDate,
  getJson,
  Input,
  Popup,
  setOptions /* localeImport */,
} from '@mobiscroll/react';
import { useCallback, useMemo, useRef, useState } from 'react';
import './searching-events-in-popup.css';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const [calEvents, setCalEvents] = useState([]);
  const [isPopupOpen, setPopupOpen] = useState(false);
  const [listEvents, setListEvents] = useState([]);
  const [searchInput, setSearchInput] = useState(null);
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [selectedEvent, setSelectedEvent] = useState([]);

  const timer = useRef(null);

  const calView = useMemo(() => ({ calendar: { labels: true } }), []);
  const listView = useMemo(() => ({ agenda: { type: 'year', size: 5 } }), []);

  const handleInputChange = useCallback((ev) => {
    const searchText = ev.target.value;

    clearTimeout(timer.current);
    timer.current = setTimeout(() => {
      if (searchText.length > 0) {
        getJson(
          'https://trial.mobiscroll.com/searchevents/?text=' + searchText,
          (data) => {
            setListEvents(data);
            setPopupOpen(true);
          },
          'jsonp',
        );
      } else {
        setPopupOpen(false);
      }
    }, 200);
  }, []);

  const handleInputFocus = useCallback((ev) => {
    if (ev.target.value.length > 0) {
      setPopupOpen(true);
    }
  }, []);

  const handlePageLoading = useCallback((args) => {
    const start = formatDate('YYYY-MM-DD', args.viewStart);
    const end = formatDate('YYYY-MM-DD', args.viewEnd);

    setTimeout(() => {
      getJson(
        'https://trial.mobiscroll.com/searchevents/?start=' + start + '&end=' + end,
        (data) => {
          setCalEvents(data);
        },
        'jsonp',
      );
    });
  }, []);

  const handlePopupClose = useCallback(() => {
    setPopupOpen(false);
  }, []);

  const handleEventClick = useCallback((args) => {
    setSelectedDate(args.event.start);
    setSelectedEvent([args.event]);
    setPopupOpen(false);
  }, []);

  const searchInputRef = useCallback((input) => {
    setSearchInput(input && input.nativeElement);
  }, []);

  const customHeader = useCallback(
    () => (
      <>
        <CalendarNav />
        <div className="mds-search-bar mbsc-flex-1-0">
          <Input
            autoComplete="off"
            inputStyle="box"
            placeholder="Search events"
            startIcon="material-search"
            ref={searchInputRef}
            onChange={handleInputChange}
            onFocus={handleInputFocus}
          />
        </div>
        <CalendarPrev />
        <CalendarToday />
        <CalendarNext />
      </>
    ),
    [handleInputChange, handleInputFocus, searchInputRef],
  );

  return (
    <>
      <Eventcalendar
        clickToCreate={false}
        dragToCreate={false}
        dragToMove={false}
        dragToResize={false}
        data={calEvents}
        renderHeader={customHeader}
        selectedDate={selectedDate}
        selectedEvents={selectedEvent}
        selectMultipleEvents={true}
        view={calView}
        onPageLoading={handlePageLoading}
      />
      <Popup
        anchor={searchInput}
        contentPadding={false}
        display="anchored"
        focusElm={searchInput}
        focusOnOpen={false}
        focusOnClose={false}
        isOpen={isPopupOpen}
        scrollLock={false}
        showArrow={false}
        showOverlay={false}
        width={400}
        onClose={handlePopupClose}
      >
        <Eventcalendar
          className="mds-search-results"
          data={listEvents}
          showControls={false}
          view={listView}
          onEventClick={handleEventClick}
        />
      </Popup>
    </>
  );
}

export default App;

// mobiscroll-demos-vue/src/demos/eventcalendar/agenda/searching-events-in-popup/searching-events-in-popup.vue
<script setup>
import {
  formatDate,
  getJson,
  MbscCalendarNav,
  MbscCalendarNext,
  MbscCalendarPrev,
  MbscCalendarToday,
  MbscEventcalendar,
  MbscInput,
  MbscPage,
  MbscPopup,
  setOptions /* localeImport */
} from '@mobiscroll/vue'
import { ref } from 'vue'
import './searching-events-in-popup.css'

setOptions({
  // locale,
  // theme
})

const calEvents = ref([])
const isPopupOpen = ref(false)
const listEvents = ref([])
const searchInput = ref(null)
const selectedDate = ref(new Date())
const selectedEvent = ref([])

const timer = ref(null)

const inputRef = ref(null)

const calView = { agenda: { type: 'month' } }
const listView = { agenda: { type: 'year', size: 5 } }

function handleInputChange(ev) {
  const searchText = ev.target.value

  if (timer.value) {
    clearTimeout(timer.value)
    timer.value = null
  }

  timer.value = setTimeout(() => {
    if (searchText.length > 0) {
      getJson(
        'https://trial.mobiscroll.com/searchevents/?text=' + searchText,
        (data) => {
          listEvents.value = data
          isPopupOpen.value = true
        },
        'jsonp'
      )
    } else {
      isPopupOpen.value = false
    }
  }, 200)
}

function handleInputFocus(ev) {
  if (ev.target.value.length > 0) {
    isPopupOpen.value = true
  }
}

function handlePageLoading(args) {
  const start = formatDate('YYYY-MM-DD', args.viewStart)
  const end = formatDate('YYYY-MM-DD', args.viewEnd)

  setTimeout(() => {
    getJson(
      'https://trial.mobiscroll.com/searchevents/?start=' + start + '&end=' + end,
      (data) => {
        calEvents.value = data
      },
      'jsonp'
    )
  })
}

function handlePopupClose() {
  isPopupOpen.value = false
}

function handleEventClick(args) {
  selectedDate.value = args.event.start
  selectedEvent.value = [args.event]
  isPopupOpen.value = false
}

function handlePopupInit() {
  setTimeout(() => {
    searchInput.value = inputRef.value.instance.nativeElement
  })
}
</script>

<template>
  <MbscPage>
    <MbscEventcalendar
      :clickToCreate="false"
      :data="calEvents"
      :dragToCreate="false"
      :dragToMove="false"
      :dragToResize="false"
      :selectMultipleEvents="true"
      :view="calView"
      :selectedEvents="selectedEvent"
      :selectedDate="selectedDate"
      @page-loading="handlePageLoading"
    >
      <template #header>
        <MbscCalendarNav />
        <div className="mds-search-bar mbsc-flex-1-0">
          <MbscInput
            autocomplete="off"
            inputStyle="box"
            placeholder="Search events"
            startIcon="material-search"
            ref="inputRef"
            @input="handleInputChange"
            @focus="handleInputFocus"
          />
        </div>
        <MbscCalendarPrev />
        <MbscCalendarToday />
        <MbscCalendarNext />
      </template>
    </MbscEventcalendar>
    <MbscPopup
      className="mds-search-popup"
      display="anchored"
      :showArrow="false"
      :showOverlay="false"
      :scrollLock="false"
      :contentPadding="false"
      :focusOnOpen="false"
      :focusOnClose="false"
      :anchor="searchInput"
      :focusElm="searchInput"
      :isOpen="isPopupOpen"
      @init="handlePopupInit"
      @close="handlePopupClose"
    >
      <MbscEventcalendar
        className="mds-search-results mbsc-popover-list"
        :view="listView"
        :data="listEvents"
        :showControls="false"
        @event-click="handleEventClick"
      />
    </MbscPopup>
  </MbscPage>
</template>
