// angular/src/demos/calendar/calendar/setting-the-picker-timezone/setting-the-picker-timezone.ts
import { Component } from '@angular/core';
import { MbscDatepickerOptions, momentTimezone /* localeImport */ } from '@mobiscroll/angular';
import moment from 'moment-timezone';

momentTimezone.moment = moment;

@Component({
  selector: 'app-calendar-setting-the-picker-timezone',
  templateUrl: './setting-the-picker-timezone.html',
})
export class AppComponent {
  options: MbscDatepickerOptions = {
    // locale,
    // theme,
    timezonePlugin: momentTimezone,
    dataTimezone: 'utc',
    displayTimezone: 'local',
    controls: ['calendar', 'time'],
  };
  selected = null;
}

// react/src/demos/datepicker/calendar/setting-the-picker-timezone/setting-the-picker-timezone.jsx
import React from 'react';
import { Datepicker, momentTimezone } from '@mobiscroll/react';
import moment from 'moment-timezone';

// setup Mobiscroll Timezone plugin with Moment
momentTimezone.moment = moment;

function App() {
  const [selected, setSelected] = React.useState(null);
  const selectedChange = (ev) => {
    setSelected(ev.value);
  };
  return (
    <Datepicker
      value={selected}
      onChange={selectedChange}
      dataTimezone="utc"
      displayTimezone="local"
      timezonePlugin={momentTimezone}
      controls={['calendar', 'time']}
    />
  );
}
