// mobiscroll-demos-react/src/demos/eventcalendar/calendar-view/cell-template-on-hover/cell-template-on-hover.jsx
import { Eventcalendar, formatDate, setOptions, Toast /* localeImport */ } from '@mobiscroll/react';
import { useCallback, useMemo, useState } from 'react';
import './cell-template-on-hover.css';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const [hoveredDate, setHoveredDate] = useState(null);
  const [isToastOpen, setToastOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState('');
  const [myEvents, setEvents] = useState(
    () => [
      {
        start: 'dyndatetime(y,m,2,12)',
        end: 'dyndatetime(y,m,2,16)',
        title: 'Company Strategy Offsite',
        color: '#90bcff',
      },
      {
        start: 'dyndatetime(y,m,7,9)',
        end: 'dyndatetime(y,m,7,17)',
        title: 'R&D Innovation Workshop',
        color: '#ffdfaf',
      },
      {
        start: 'dyndatetime(y,m,15,10)',
        end: 'dyndatetime(y,m,15,15)',
        title: 'Client Feedback Review',
        color: '#ffb9ad',
      },
      {
        start: 'dyndatetime(y,m,19,9)',
        end: 'dyndatetime(y,m,19,19)',
        title: 'Team Building Adventure',
        color: '#f3c1ff',
      },
      {
        start: 'dyndatetime(y,m,23,11)',
        end: 'dyndatetime(y,m,23,15)',
        title: 'Sales Summit & Training',
        color: '#b5eff8',
      },
      {
        start: 'dyndatetime(y,m,25,10)',
        end: 'dyndatetime(y,m,25,15)',
        title: 'Executive Planning Retreat',
        color: '#c7ffbb',
      },
      {
        start: 'dyndatetime(y,m,29,14)',
        end: 'dyndatetime(y,m,29,17)',
        title: 'Marketing Team Conference',
        color: '#ffeeb6',
      },
    ],
    [],
  );

  const myView = useMemo(
    () => ({
      calendar: {
        labels: 2,
      },
    }),
    [],
  );

  const addEvent = useCallback(() => {
    const newEvent = {
      start: hoveredDate,
      title: 'New Event',
    };

    setEvents((myEvents) => [...myEvents, newEvent]);
    setToastMessage('Event added on ' + formatDate('YYYY-MM-DD', hoveredDate));
    setToastOpen(true);
  }, [hoveredDate]);

  const customDayContent = useCallback(
    (args) => {
      const isHovered = hoveredDate && hoveredDate.getTime() === args.date.getTime();

      return (
        isHovered && (
          <button onClick={addEvent} className="mds-cell-summary-btn">
            Add event
          </button>
        )
      );
    },
    [hoveredDate, addEvent],
  );

  const handleCellHoverIn = useCallback((args) => {
    setHoveredDate(args.date);
  }, []);

  const handleCellHoverOut = useCallback(() => {
    setHoveredDate(null);
  }, []);

  const handleToastClose = () => {
    setToastOpen(false);
  };

  return (
    <>
      <Eventcalendar
        data={myEvents}
        view={myView}
        className="mds-cell-summary"
        renderDayContent={customDayContent}
        onCellHoverIn={handleCellHoverIn}
        onCellHoverOut={handleCellHoverOut}
      />
      <Toast isOpen={isToastOpen} message={toastMessage} onClose={handleToastClose} />
    </>
  );
}

export default App;

// mobiscroll-demos-vue/src/demos/eventcalendar/calendar-view/cell-template-on-hover/cell-template-on-hover.vue
<script setup>
import {
  formatDate,
  MbscEventcalendar,
  MbscToast,
  setOptions /* localeImport */
} from '@mobiscroll/vue'
import { ref } from 'vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([
  {
    start: 'dyndatetime(y,m,2,12)',
    end: 'dyndatetime(y,m,2,16)',
    title: 'Company Strategy Offsite',
    color: '#90bcff'
  },
  {
    start: 'dyndatetime(y,m,7,9)',
    end: 'dyndatetime(y,m,7,17)',
    title: 'R&D Innovation Workshop',
    color: '#ffdfaf'
  },
  {
    start: 'dyndatetime(y,m,15,10)',
    end: 'dyndatetime(y,m,15,15)',
    title: 'Client Feedback Review',
    color: '#ffb9ad'
  },
  {
    start: 'dyndatetime(y,m,19,9)',
    end: 'dyndatetime(y,m,19,19)',
    title: 'Team Building Adventure',
    color: '#f3c1ff'
  },
  {
    start: 'dyndatetime(y,m,23,11)',
    end: 'dyndatetime(y,m,23,15)',
    title: 'Sales Summit & Training',
    color: '#b5eff8'
  },
  {
    start: 'dyndatetime(y,m,25,10)',
    end: 'dyndatetime(y,m,25,15)',

    title: 'Executive Planning Retreat',
    color: '#c7ffbb'
  },
  {
    start: 'dyndatetime(y,m,29,14)',
    end: 'dyndatetime(y,m,29,17)',
    title: 'Marketing Team Conference',
    color: '#ffeeb6'
  }
])

const hoveredDate = ref(null)
const isToastOpen = ref(false)
const toastMessage = ref('')

const myView = {
  calendar: {
    labels: 2
  }
}

function addEvent() {
  const newEvent = {
    start: hoveredDate.value,
    title: 'New Event'
  }
  myEvents.value = [...myEvents.value, newEvent]
  toastMessage.value = 'Event added on ' + formatDate('YYYY-MM-DD', hoveredDate.value)
  isToastOpen.value = true
}

// Mobiscroll resource hover events
function handleCellHoverIn(args) {
  hoveredDate.value = args.date
}

function handleCellHoverOut() {
  hoveredDate.value = null
}

function handleToastClose() {
  isToastOpen.value = false
}

function isHovered(date) {
  return hoveredDate.value && hoveredDate.value.getTime() === date.getTime()
}
</script>

<template>
  <MbscEventcalendar
    cssClass="mds-cell-summary"
    :view="myView"
    :data="myEvents"
    @cell-hover-in="handleCellHoverIn"
    @cell-hover-out="handleCellHoverOut"
  >
    <template #dayContent="args">
      <button @click="addEvent" class="mds-cell-summary-btn" v-if="isHovered(args.date)">
        Add event
      </button>
    </template>
  </MbscEventcalendar>
  <MbscToast :isOpen="isToastOpen" :message="toastMessage" @close="handleToastClose" />
</template>

<style>
.mds-cell-summary .mbsc-calendar-cell {
  min-height: 145px;
}
.mds-cell-summary-btn {
  position: absolute;
  left: 10px;
  right: 10px;
  bottom: 8px;
  z-index: 3;
  font-size: 10px;
  padding: 8px;
  background: transparent;
  border-radius: 4px;
  border: 1px solid #5584b5;
  color: #5584b5;
  text-transform: uppercase;
  cursor: pointer;
  transition: background-color 0.1s ease-out;
}
.mds-cell-summary-btn:hover {
  background: #5584b5;
  color: white;
  box-shadow: 0 2px 8px rgba(85, 132, 181, 0.3);
}
.mds-cell-summary-btn:active {
  box-shadow: 0 1px 4px rgba(85, 132, 181, 0.3);
}
</style>
