// vue-ts/src/demos/eventcalendar/eventcalendar/quarter-year-view/quarter-year-view.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import {
  MbscEventcalendar,
  MbscCalendarNav,
  MbscCalendarPrev,
  MbscCalendarNext,
  MbscCalendarToday,
  setOptions,
  MbscSegmentedGroup,
  MbscSegmented,
  getJson /* localeImport */
} from '@mobiscroll/vue'
import type { MbscCalendarEvent, MbscEventcalendarView } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref<MbscCalendarEvent[]>([])
const calendarType = ref<string>('quarter')
const calHeight = ref<string>('auto')

const myView = ref<MbscEventcalendarView>({
  calendar: {
    type: 'month',
    size: 3
  }
})

function changeView() {
  switch (calendarType.value) {
    case 'quarter':
      myView.value = {
        calendar: {
          type: 'month',
          size: 3
        }
      }
      calHeight.value = 'auto'
      break
    case 'year':
      myView.value = {
        calendar: {
          type: 'year'
        }
      }
      calHeight.value = '100%'
      break
  }
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events: MbscCalendarEvent[]) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <MbscEventcalendar :data="myEvents" :view="myView" :height="calHeight">
    <template #header>
      <MbscCalendarNav />
      <div class="quarter-year-header-picker">
        <MbscSegmentedGroup v-model="calendarType" @change="changeView()">
          <MbscSegmented value="quarter">Quarter</MbscSegmented>
          <MbscSegmented value="year">Year</MbscSegmented>
        </MbscSegmentedGroup>
      </div>
      <MbscCalendarPrev />
      <MbscCalendarToday />
      <MbscCalendarNext />
    </template>
  </MbscEventcalendar>
</template>

<style>
.mbsc-calendar .quarter-year-header-picker .mbsc-segmented {
  max-width: 200px;
  margin: 0 auto;
}

.quarter-year-header-picker {
  flex: 1 0 auto;
}
</style>

// react-ts/src/demos/eventcalendar/eventcalendar/quarter-year-view/quarter-year-view.tsx
import React from 'react';
import {
  Eventcalendar,
  CalendarPrev,
  CalendarNav,
  CalendarNext,
  CalendarToday,
  SegmentedGroup,
  SegmentedItem,
  getJson,
  MbscCalendarEvent,
  MbscEventcalendarView,
  setOptions /* localeImport */,
} from '@mobiscroll/react';
import './quarter-year-view.css';
setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => {
  const [calendarType, setCalendarType] = React.useState<string>('quarter');
  const [myEvents, setEvents] = React.useState<MbscCalendarEvent[]>([]);

  const view = React.useMemo<MbscEventcalendarView>(
    () =>
      calendarType === 'quarter'
        ? {
            calendar: {
              type: 'month',
              size: 3,
            },
          }
        : {
            calendar: {
              type: 'year',
            },
          },
    [calendarType],
  );

  const calHeight = React.useMemo<string>(() => (calendarType === 'quarter' ? 'auto' : 'height:100%'), [calendarType]);

  const calendarHeaderSwitch = () => {
    return (
      <React.Fragment>
        <CalendarNav />
        <div className="quarter-year-header-picker">
          <SegmentedGroup value={calendarType} onChange={changeView}>
            <SegmentedItem value="quarter">Quarter</SegmentedItem>
            <SegmentedItem value="year">Year</SegmentedItem>
          </SegmentedGroup>
        </div>
        <CalendarPrev />
        <CalendarToday />
        <CalendarNext />
      </React.Fragment>
    );
  };

  const changeView = (event: any) => {
    setCalendarType(event.target.value);
  };

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events: MbscCalendarEvent[]) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  return <Eventcalendar data={myEvents} view={view} height={calHeight} renderHeader={calendarHeaderSwitch} />;
};
