// react/src/demos/range/range/gregorian-jalali-hijri/gregorian-jalali-hijri.jsx
import React from 'react';
import { Datepicker, setOptions, jalaliCalendar, hijriCalendar, localeFa, localeAr /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // themeJs
});

function App() {
  return (
    <div>
      <Datepicker controls={['calendar']} select="range" display="inline" />
      <Datepicker controls={['calendar']} select="range" display="inline" calendarSystem={jalaliCalendar} locale={localeFa} />
      <Datepicker controls={['calendar']} select="range" display="inline" calendarSystem={hijriCalendar} locale={localeAr} />
    </div>
  );
}

export default App;

// vue-ts/src/demos/range/range/gregorian-jalali-hijri/gregorian-jalali-hijri.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  MbscDatepicker,
  setOptions,
  jalaliCalendar,
  hijriCalendar,
  localeFa,
  localeAr
} from '@mobiscroll/vue'

setOptions({
  // theme
})
</script>

<template>
  <MbscDatepicker display="inline" select="range" :controls="['calendar']" />
  <MbscDatepicker
    display="inline"
    select="range"
    :controls="['calendar']"
    :calendarSystem="jalaliCalendar"
    :locale="localeFa"
  />
  <MbscDatepicker
    display="inline"
    select="range"
    :controls="['calendar']"
    :calendarSystem="hijriCalendar"
    :locale="localeAr"
  />
</template>
