// react/src/demos/eventcalendar/eventcalendar/setting-the-timezone/setting-the-timezone.jsx
import { Eventcalendar, momentTimezone, setOptions /* localeImport */ } from '@mobiscroll/react';
import moment from 'moment-timezone';
import { useMemo } from 'react';

momentTimezone.moment = moment;

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const myEvents = useMemo(
    () => [
      {
        start: 'dyndatetime(y, m, d, 7)',
        end: 'dyndatetime(y, m, d, 9)',
        title: 'Stakeholder mtg.',
        color: '#d64646',
      },
      {
        start: 'dyndatetime(y, m, d+3, 18)',
        end: 'dyndatetime(y, m, d+3, 19, 30)',
        title: 'Wrapup mtg.',
        color: '#ecbc72',
      },
      {
        start: 'dyndatetime(y, m, d, 14)',
        end: 'dyndatetime(y, m, d, 18)',
        title: 'Business of Software Conference',
        color: '#ff6d42',
      },
      {
        start: 'dyndatetime(y, m, d+1, 20)',
        end: 'dyndatetime(y, m, d+1, 21, 50)',
        title: 'Product Team mtg.',
        color: '#913aa7',
      },
      {
        start: 'dyndatetime(y, m, d-1, 13)',
        end: 'dyndatetime(y, m, d-1, 15)',
        title: 'Decision Making mtg.',
        color: '#46c3d6',
      },
      {
        start: 'dyndatetime(y, m, d+1, 13)',
        end: 'dyndatetime(y, m, d+1, 14)',
        title: 'Quick mtg. with Martin',
        color: '#50b166',
      },
      {
        start: 'dyndatetime(y, m, d+3, 12)',
        end: 'dyndatetime(y, m, d+3, 16)',
        color: '#5bb7c5',
        title: 'Team-Building',
      },
    ],
    [],
  );

  const myView = useMemo(() => ({ calendar: { popover: true, type: 'month' } }), []);

  return <Eventcalendar dataTimezone="utc" displayTimezone="local" timezonePlugin={momentTimezone} data={myEvents} view={myView} />;
}

export default App;

// vue/src/demos/eventcalendar/eventcalendar/setting-the-timezone/setting-the-timezone.vue
<script setup>
import { MbscEventcalendar, momentTimezone /* localeImport */ } from '@mobiscroll/vue'
import * as moment from 'moment-timezone'

momentTimezone.moment = moment

const myEvents = [
  {
    start: 'dyndatetime(y, m, d, 7)',
    end: 'dyndatetime(y, m, d, 9)',
    title: 'Stakeholder mtg.',
    color: '#d64646'
  },
  {
    start: 'dyndatetime(y, m, d+3, 18)',
    end: 'dyndatetime(y, m, d+3, 19, 30)',
    title: 'Wrapup mtg.',
    color: '#ecbc72'
  },
  {
    start: 'dyndatetime(y, m, d, 14)',
    end: 'dyndatetime(y, m, d, 18)',
    title: 'Business of Software Conference',
    color: '#ff6d42'
  },
  {
    start: 'dyndatetime(y, m, d+1, 20)',
    end: 'dyndatetime(y, m, d+1, 21, 50)',
    title: 'Product Team mtg.',
    color: '#913aa7'
  },
  {
    start: 'dyndatetime(y, m, d-1, 13)',
    end: 'dyndatetime(y, m, d-1, 15)',
    title: 'Decision Making mtg.',
    color: '#46c3d6'
  },
  {
    start: 'dyndatetime(y, m, d+1, 13)',
    end: 'dyndatetime(y, m, d+1, 14)',
    title: 'Quick mtg. with Martin',
    color: '#50b166'
  },
  {
    start: 'dyndatetime(y, m, d+3, 12)',
    end: 'dyndatetime(y, m, d+3, 16)',
    color: '#5bb7c5',
    title: 'Team-Building'
  }
]

const myView = {
  calendar: {
    popover: true,
    type: 'month'
  }
}
</script>

<template>
  <MbscEventcalendar
    :drag="drag"
    :view="myView"
    :data="myEvents"
    :timezonePlugin="momentTimezone"
    dataTimezone="utc"
    displayTimezone="local"
  />
</template>
