// react-ts/src/demos/datetime/datetime/date-picker/date-picker.tsx
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';
import React from 'react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => (
  <Page>
    <Datepicker
      controls={['date']}
      inputProps={{
        label: 'Date picker',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['date']}
      dateFormat="MM/YYYY"
      dateWheels="MMMM YYYY"
      inputProps={{
        label: 'Month & year picker',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
  </Page>
);
export default App;

// mobiscroll-demos-vue/src/demos/datepicker/datetime/date-picker/date-picker.vue
<script setup>
import { MbscDatepicker, MbscPage, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscPage>
    <MbscDatepicker
      :controls="['date']"
      label="Date picker"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['date']"
      dateFormat="MM/YYYY"
      dateWheels="MMMM YYYY"
      label="Month & year picker"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
  </MbscPage>
</template>
