// angular/src/demos/eventcalendar/eventcalendar/event-hooks/event-hooks.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { setOptions, MbscEventcalendarView, MbscCalendarEvent /* localeImport */ } from '@mobiscroll/angular';
import { HttpClient } from '@angular/common/http';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'app-eventcalendar-event-hooks',
  styleUrl: './event-hooks.css',
  encapsulation: ViewEncapsulation.None,
  templateUrl: './event-hooks.html',
})
export class AppComponent implements OnInit {
  constructor(private http: HttpClient) {}

  myEvents: MbscCalendarEvent[] = [];

  invalid = [
    {
      recurring: {
        repeat: 'weekly',
        weekDays: 'SA,SU',
      },
    },
  ];

  view: MbscEventcalendarView = {
    calendar: { labels: true },
  };

  onCellClick(): void {
    // Logic for event click
  }
  onCellDoubleClick(): void {
    /* Logic for cell double click */
  }
  onCellRightClick(): void {
    /* Logic for cell right click */
  }
  onCellHoverIn(): void {
    /* Logic for cell hover in */
  }
  onCellHoverOut(): void {
    /* Logic for cell hover in */
  }
  onDestroy(): void {
    // Logic for destroying the event calendar
  }
  onEventClick(): void {
    // Logic for event click
  }
  onEventCreate(): void {
    // Logic for event create
  }
  onEventCreated(): void {
    // Logic for event created
  }
  onEventCreateFailed(): void {
    // Logic for failed event create
  }
  onEventDelete(): void {
    // Logic for event delete
  }
  onEventDeleted(): void {
    // Logic for event deleted
  }
  onEventDoubleClick(): void {
    // Logic for event double click
  }
  onEventDragStart(): void {
    // Logic for event drag start
  }
  onEventDragEnd(): void {
    // Logic for event drag end
  }
  onEventHoverIn(): void {
    // Logic for event hover in
  }
  onEventHoverOut(): void {
    // Logic for event hover out
  }
  onEventUpdate(): void {
    // Logic for event update
  }
  onEventUpdated(): void {
    // Logic for event updated
  }
  onEventUpdateFailed(): void {
    // Logic for failed event update
  }
  onEventRightClick(): void {
    // Logic for event right click
  }
  onInit(): void {
    // Logic running on component init
  }
  onLabelClick(): void {
    // Logic for label click
  }
  onPageChange(): void {
    // Your custom event handler goes here
  }
  onPageLoaded(): void {
    // Use it to inject custom markup & attach custom listeners
  }
  onPageLoading(): void {
    // Use it to load data on demand
  }
  onSelectedDateChange(): void {
    // Use it to keep track of the selected date externally
  }

  dragData1 = {
    title: 'External drag 1',
    color: '#ffdab8',
  };

  dragData2 = {
    title: 'External drag 2',
    color: '#ddfcf7',
  };

  ngOnInit(): void {
    this.http.jsonp<MbscCalendarEvent[]>('https://trial.mobiscroll.com/events/?vers=5', 'callback').subscribe((resp) => {
      this.myEvents = resp;
    });
  }
}

// react-ts/src/demos/eventcalendar/eventcalendar/event-hooks/event-hooks.tsx
import React from 'react';
import { Eventcalendar, Draggable, getJson, MbscCalendarEvent, MbscEventcalendarView /* localeImport */ } from '@mobiscroll/react';
import './event-hooks.css';

const App: React.FC = () => {
  const [myEvents, setEvents] = React.useState<MbscCalendarEvent[]>([]);

  const invalid = [
    {
      recurring: {
        repeat: 'weekly',
        weekDays: 'SA,SU',
      },
    },
  ];

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events: MbscCalendarEvent[]) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  const view = React.useMemo<MbscEventcalendarView>(() => {
    return {
      calendar: { labels: true },
    };
  }, []);

  const [draggable1, setDraggable1] = React.useState<any>();
  const [draggable2, setDraggable2] = React.useState<any>();

  const setDragElm1 = React.useCallback((elm) => {
    setDraggable1(elm);
  }, []);

  const setDragElm2 = React.useCallback((elm) => {
    setDraggable2(elm);
  }, []);

  const dragData1 = {
    title: 'External drag 1',
    color: '#ffdab8',
  };

  const dragData2 = {
    title: 'External drag 2',
    color: '#ddfcf7',
  };

  return (
    <>
      <div ref={setDraggable1} className="event-hooks-draggable" style={{ background: '#ffdab8' }}>
        <div className="draggable-title">External drag 1</div>
        <div className="draggable-text">Drag me to calendar</div>
        <Draggable dragData={dragData1} element={draggable1} />
      </div>
      <div ref={setDraggable2} className="event-hooks-draggable" style={{ background: '#ddfcf7' }}>
        <div className="draggable-title">External drag 2</div>
        <div className="draggable-text">Drag me to calendar</div>
        <Draggable dragData={dragData2} element={draggable2} />
      </div>
      <Eventcalendar
        // theme
        // locale
        data={myEvents}
        dragToCreate={true}
        dragToMove={true}
        dragToResize={true}
        externalDrop={true}
        view={view}
        invalid={invalid}
        onCellClick={(event, inst) => {
          // Logic for event click
        }}
        onCellDoubleClick={(event, inst) => {
          /* Logic for cell double click */
        }}
        onCellRightClick={(event, inst) => {
          /* Logic for cell right click */
        }}
        onCellHoverIn={(event, inst) => {
          /* Logic for cell hover in */
        }}
        onCellHoverOut={(event, inst) => {
          /* Logic for cell hover out */
        }}
        onDestroy={(event, inst) => {
          // Your custom event handler goes here
        }}
        onEventClick={(event, inst) => {
          // Logic for event click
        }}
        onEventCreate={(event, inst) => {
          // Logic for event create
        }}
        onEventCreated={(event, inst) => {
          // Logic for event created
        }}
        onEventCreateFailed={(event, inst) => {
          // Logic for failed event create
        }}
        onEventDelete={(event, inst) => {
          // Logic for event delete
        }}
        onEventDeleted={(event, inst) => {
          // Logic for event deleted
        }}
        onEventDoubleClick={(event, inst) => {
          // Logic for event double click
        }}
        onEventDragStart={(event, inst) => {
          // Logic for event drag start
        }}
        onEventDragEnd={(event, inst) => {
          // Logic for event drag end
        }}
        onEventHoverIn={(event, inst) => {
          // Logic for event hover in
        }}
        onEventHoverOut={(event, inst) => {
          // Logic for event hover out
        }}
        onEventUpdate={(event, inst) => {
          // Logic for event update
        }}
        onEventUpdated={(event, inst) => {
          // Logic for event updated
        }}
        onEventUpdateFailed={(event, inst) => {
          // Logic for failed event update
        }}
        onEventRightClick={(event, inst) => {
          // Logic for event right click
        }}
        onInit={(event, inst) => {
          // Logic running on component init
        }}
        onLabelClick={(event, inst) => {
          // Logic for label click
        }}
        onPageChange={(event, inst) => {
          // Your custom event handler goes here
        }}
        onPageLoaded={(event, inst) => {
          // Use it to inject custom markup & attach custom listeners
        }}
        onPageLoading={(event, inst) => {
          // Use it to load data on demand
        }}
        onSelectedDateChange={(event, inst) => {
          // Use it to keep track of the selected date externally
        }}
      />
    </>
  );
};
export default App;
