// react/src/demos/datetime/datetime/gregorian-jalali-hijri/gregorian-jalali-hijri.jsx
import React from 'react';
import { Datepicker, setOptions, jalaliCalendar, hijriCalendar, localeFa, localeAr /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // themeJs
});

function App() {
  return (
    <div>
      <Datepicker controls={['date']} display="inline" />
      <Datepicker controls={['date']} display="inline" calendarSystem={jalaliCalendar} locale={localeFa} />
      <Datepicker controls={['date']} display="inline" calendarSystem={hijriCalendar} locale={localeAr} />
    </div>
  );
}

export default App;

// mobiscroll-demos-vue/src/demos/datepicker/datetime/gregorian-jalali-hijri/gregorian-jalali-hijri.vue
<script setup>
import {
  hijriCalendar,
  jalaliCalendar,
  localeAr,
  localeFa,
  MbscDatepicker,
  setOptions
} from '@mobiscroll/vue'

setOptions({
  // theme
})
</script>

<template>
  <MbscDatepicker display="inline" :controls="['date']" />
  <MbscDatepicker
    display="inline"
    :controls="['date']"
    :calendarSystem="jalaliCalendar"
    :locale="localeFa"
  />
  <MbscDatepicker
    display="inline"
    :controls="['date']"
    :calendarSystem="hijriCalendar"
    :locale="localeAr"
  />
</template>
