// react/src/demos/eventcalendar/eventcalendar/conditional-move-resize/conditional-move-resize-drag-drop-fixed-event-length-fixed-to-resource.jsx
import { Eventcalendar, setOptions /* localeImport */ } from '@mobiscroll/react';
import { useMemo } from 'react';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const myView = useMemo(() => ({ calendar: { type: 'month' } }), []);

  const myEvents = useMemo(
    () => [
      {
        color: 'cyan',
        end: 'dyndatetime(y,m,d-5)',
        start: 'dyndatetime(y,m,d-6)',
        title: 'Event 1',
      },
      {
        color: 'blue',
        dragInTime: false,
        end: 'dyndatetime(y,m,d-1)',
        start: 'dyndatetime(y,m,d-4)',
        title: 'Event 2 (cannot be moved in time)',
      },
      {
        color: 'brown',
        end: 'dyndatetime(y,m,d+3)',
        start: 'dyndatetime(y,m,d)',
        resize: false,
        title: 'Event 3 (cannot be resized)',
      },
      {
        color: 'teal',
        end: 'dyndatetime(y,m,d+4)',
        start: 'dyndatetime(y,m,d+3)',
        title: 'Event 4',
      },
      {
        color: 'yellow',
        end: 'dyndatetime(y,m,d+6)',
        start: 'dyndatetime(y,m,d+5)',
        title: 'Event 5',
      },
    ],
    [],
  );

  return <Eventcalendar view={myView} data={myEvents} dragToMove={true} />;
}

export default App;

// vue/src/demos/eventcalendar/eventcalendar/conditional-move-resize/conditional-move-resize-drag-drop-fixed-event-length-fixed-to-resource.vue
<script setup>
import { ref } from 'vue'
import { MbscEventcalendar, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const myView = {
  calendar: { type: 'month' }
}

const myEvents = ref([
  {
    color: 'cyan',
    end: 'dyndatetime(y,m,d-5)',
    start: 'dyndatetime(y,m,d-6)',
    title: 'Event 1'
  },
  {
    color: 'blue',
    dragInTime: false,
    end: 'dyndatetime(y,m,d-1)',
    start: 'dyndatetime(y,m,d-4)',
    title: 'Event 2 (cannot be moved in time)'
  },
  {
    color: 'brown',
    end: 'dyndatetime(y,m,d+3)',
    start: 'dyndatetime(y,m,d)',
    resize: false,
    title: 'Event 3 (cannot be resized)'
  },
  {
    color: 'teal',
    end: 'dyndatetime(y,m,d+4)',
    start: 'dyndatetime(y,m,d+3)',
    title: 'Event 4'
  },
  {
    color: 'yellow',
    end: 'dyndatetime(y,m,d+6)',
    start: 'dyndatetime(y,m,d+5)',
    title: 'Event 5'
  }
])
</script>

<template><MbscEventcalendar :view="myView" :data="myEvents" :dragToMove="true" /></template>
