// react/src/demos/calendar/calendar/range-select/range-select.jsx
import React from 'react';
import { Datepicker /* localeImport */ } from '@mobiscroll/react';

function App() {
  return (
    <Datepicker
      // locale
      // theme
      controls={['calendar']}
      display="inline"
      rangeSelectMode="wizard"
      select="range"
      showRangeLabels={true}
    />
  );
}

export default App;

// vue-ts/src/demos/calendar/calendar/range-select/range-select.vue
<script setup lang="ts">
import { MbscDatepicker, setOptions/* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script> 

<template>
  <MbscDatepicker
    display="inline"
    select="range"
    rangeSelectMode="wizard"
    :controls="['calendar']
    :showRangeLabels="true"
  />
</template>
