// react-ts/src/demos/eventcalendar/eventcalendar/colored-cell-background/colored-cell-background.tsx
import React from 'react';
import { Eventcalendar, getJson, MbscCalendarEvent, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

const myColors = [
  {
    start: 'dyndatetime(y,m,0)',
    end: 'dyndatetime(y,m,1)',
    background: '#fde4c880',
  },
  {
    start: 'dyndatetime(y,m,17)',
    end: 'dyndatetime(y,m,20)',
    background: '#d5f1ea80',
  },
  {
    date: 'dyndatetime(y,m,29)',
    background: '#ffdbdb80',
  },
  {
    date: 'dyndatetime(y,m+1,3)',
    background: '#fbedd080',
  },
  {
    date: 'dyndatetime(y,m+1,10)',
    background: '#fbedd080',
  },
  {
    background: '#d6e81e1a',
    recurring: {
      repeat: 'monthly',
      day: -1,
    },
  },
];

const App: React.FC = () => {
  const [myEvents, setEvents] = React.useState<MbscCalendarEvent[]>([]);

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events: MbscCalendarEvent[]) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  return (
    <Eventcalendar
      // drag
      data={myEvents}
      colors={myColors}
    />
  );
};
export default App;

// vue/src/demos/eventcalendar/eventcalendar/colored-cell-background/colored-cell-background.vue
<script setup>
import { ref, onMounted } from 'vue'
import { MbscEventcalendar, setOptions, getJson /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([])

const myColors = ref([
  {
    start: 'dyndatetime(y,m,0)',
    end: 'dyndatetime(y,m,1)',
    background: '#fde4c880'
  },
  {
    start: 'dyndatetime(y,m,17)',
    end: 'dyndatetime(y,m,20)',
    background: '#d5f1ea80'
  },
  {
    date: 'dyndatetime(y,m,29)',
    background: '#ffdbdb80'
  },
  {
    date: 'dyndatetime(y,m+1,3)',
    background: '#fbedd080'
  },
  {
    date: 'dyndatetime(y,m+1,10)',
    background: '#fbedd080'
  },
  {
    background: '#d6e81e1a',
    recurring: {
      repeat: 'monthly',
      day: -1
    }
  }
])

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template><MbscEventcalendar :drag="drag" :data="myEvents" :colors="myColors" /></template>
