// mobiscroll-demos-angular/src/demos/eventcalendar/agenda/customizing-calendar-header/customizing-calendar-header.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { MbscCalendarEvent, MbscDateType, MbscEventcalendarView, setOptions /* localeImport */ } from '@mobiscroll/angular';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'app-agenda-customizing-calendar-header',
  styleUrl: './customizing-calendar-header.css',
  encapsulation: ViewEncapsulation.None,
  templateUrl: './customizing-calendar-header.html',
})
export class AppComponent implements OnInit {
  constructor(private http: HttpClient) {}

  currentDate: MbscDateType = new Date();
  currentView = 'agenda';
  myEvents: MbscCalendarEvent[] = [];
  myView: MbscEventcalendarView = { agenda: { type: 'month' } };

  changeView(): void {
    setTimeout(() => {
      switch (this.currentView) {
        case 'calendar':
          this.myView = { calendar: { type: 'month' } };
          break;
        case 'agenda':
          this.myView = { agenda: { type: 'month' } };
          break;
      }
    });
  }

  nextPage(): void {
    const currentDate = this.currentDate as Date;
    this.currentDate = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1);
  }

  prevPage(): void {
    const currentDate = this.currentDate as Date;
    this.currentDate = new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1);
  }

  ngOnInit(): void {
    this.http.jsonp<MbscCalendarEvent[]>('https://trial.mobiscroll.com/events/?vers=5', 'callback').subscribe((resp) => {
      this.myEvents = resp;
    });
  }
}

// mobiscroll-demos-react-ts/src/demos/eventcalendar/agenda/customizing-calendar-header/customizing-calendar-header.tsx
import {
  Button,
  CalendarNav,
  CalendarToday,
  Eventcalendar,
  getJson,
  MbscCalendarEvent,
  MbscEventcalendarView,
  MbscSelectedDateChangeEvent,
  Segmented,
  SegmentedGroup,
  setOptions /* localeImport */,
} from '@mobiscroll/react';
import { ChangeEvent, FC, useCallback, useEffect, useState } from 'react';
import './customizing-calendar-header.css';

setOptions({
  // localeJs,
  // themeJs
});

const App: FC = () => {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [currentView, setCurrentView] = useState<string>('agenda');
  const [myEvents, setEvents] = useState<MbscCalendarEvent[]>([]);
  const [myView, setView] = useState<MbscEventcalendarView>({ agenda: { type: 'month' } });

  const handleSelectedDateChange = useCallback((args: MbscSelectedDateChangeEvent) => {
    setCurrentDate(args.date as Date);
  }, []);

  const changeView = useCallback((event: ChangeEvent<HTMLInputElement>) => {
    let view = {};
    switch (event.target.value) {
      case 'calendar':
        view = {
          calendar: { type: 'month' },
        };
        break;
      case 'agenda':
        view = {
          agenda: { type: 'month' },
        };
        break;
    }

    setCurrentView(event.target.value);
    setView(view);
  }, []);

  const prevPage = useCallback(() => {
    setCurrentDate((currentDate) => new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
  }, []);

  const nextPage = useCallback(() => {
    setCurrentDate((currentDate) => new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
  }, []);

  const customWithNavButtons = useCallback(
    () => (
      <>
        <CalendarNav className="mds-custom-header-nav" />
        <div className="mbsc-flex mbsc-flex-1-0 mbsc-justify-content-center">
          <Button onClick={prevPage} icon="material-arrow-back" variant="flat" className="mds-custom-header-button"></Button>
          <CalendarToday className="md-custom-header-today" />
          <Button onClick={nextPage} icon="material-arrow-forward" variant="flat" className="mds-custom-header-button"></Button>
        </div>
        <div className="mds-custom-header-switch">
          <SegmentedGroup value={currentView} onChange={changeView}>
            <Segmented value="agenda" icon="material-view-day" />
            <Segmented value="calendar" icon="calendar" />
          </SegmentedGroup>
        </div>
      </>
    ),
    [changeView, nextPage, prevPage, currentView],
  );

  useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events: MbscCalendarEvent[]) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  return (
    <Eventcalendar
      data={myEvents}
      renderHeader={customWithNavButtons}
      selectedDate={currentDate}
      view={myView}
      onSelectedDateChange={handleSelectedDateChange}
    />
  );
};

export default App;
