// mobiscroll-demos-vue-ts/src/demos/eventcalendar/agenda/full-event-customization/full-event-customization.vue
<script setup lang="ts">
import { getJson, MbscEventcalendar, setOptions /* localeImport */ } from '@mobiscroll/vue'
import type { MbscCalendarEvent, MbscEventcalendarView } from '@mobiscroll/vue'
import { onMounted, ref } from 'vue'
import './full-event-customization.css'

setOptions({
  // locale,
  // theme
})

const myEvents = ref<MbscCalendarEvent[]>([])

const myView: MbscEventcalendarView = {
  agenda: { type: 'month' }
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/agenda-events/',
    (events: MbscCalendarEvent[]) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <MbscEventcalendar :view="myView" :data="myEvents">
    <template #event="data">
      <div class="mbsc-flex mbsc-flex-1-1">
        <img
          class="mds-agenda-event-img"
          :src="'https://img.mobiscroll.com/demos/' + data.original.img"
        />
        <div class="mbsc-flex-1-1">
          <div class="mds-agenda-event-title">{{ data.title }}</div>
          <div class="mbsc-flex">
            <div class="mds-agenda-event-location mbsc-flex-1-1">
              <div class="mds-agenda-event-label">Location</div>
              <div>{{ data.original.location }}</div>
            </div>
            <div class="mds-agenda-event-time">
              <div class="mds-agenda-event-label">Time</div>
              <div>{{ data.start }}</div>
            </div>
          </div>
        </div>
      </div>
    </template>
  </MbscEventcalendar>
</template>

// react-ts/src/demos/eventcalendar/agenda/full-event-customization/full-event-customization.tsx
import React from 'react';
import { Eventcalendar, getJson, setOptions, MbscCalendarEvent, MbscEventcalendarView /* localeImport */ } from '@mobiscroll/react';
import './full-event-customization.css';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => {
  const [myEvents, setEvents] = React.useState<MbscCalendarEvent[]>([]);

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/agenda-events/',
      (events: MbscCalendarEvent[]) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  const [calView, setCalView] = React.useState<MbscEventcalendarView>({
    agenda: { type: 'month' },
  });

  const renderEvent = React.useCallback((data) => {
    return (
      <div className="md-full-event">
        <img className="md-full-event-img" src={'https://img.mobiscroll.com/demos/' + data.original.img} />
        <div className="md-full-event-details">
          <div className="md-full-event-title">{data.title}</div>
          <div className="md-full-event-location">
            <div className="md-full-event-label">Location</div>
            <div>{data.original.location}</div>
          </div>
          <div className="md-full-event-time">
            <div className="md-full-event-label">Time</div>
            <div>{data.start}</div>
          </div>
        </div>
      </div>
    );
  }, []);

  return <Eventcalendar renderEvent={renderEvent} view={calView} data={myEvents} />;
};
export default App;
