// react/src/demos/calendar/calendar/single-select/single-select.jsx
import React from 'react';
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  return (
    <Page>
      <Datepicker
        controls={['calendar']}
        selectMultiple={false}
        inputProps={{
          label: 'Date',
          inputStyle: 'box',
          labelStyle: 'stacked',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['calendar', 'time']}
        selectMultiple={false}
        inputProps={{
          label: 'Date & time',
          inputStyle: 'box',
          labelStyle: 'stacked',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['calendar', 'timegrid']}
        selectMultiple={false}
        inputProps={{
          label: 'Date & timegrid',
          inputStyle: 'box',
          labelStyle: 'stacked',
          placeholder: 'Please Select...',
        }}
      />
    </Page>
  );
}

export default App;

// vue-ts/src/demos/calendar/calendar/single-select/single-select.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MbscDatepicker, MbscPage, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscPage>
    <MbscDatepicker
      :controls="['calendar']"
      :selectMultiple="false"
      label="Date"
      placeholder="Please Select..."
      inputStyle="box"
      labelStyle="stacked"
    />
    <MbscDatepicker
      :controls="['calendar', 'time']"
      :selectMultiple="false"
      label="Date & Time"
      placeholder="Please Select..."
      inputStyle="box"
      labelStyle="stacked"
    />
    <MbscDatepicker
      :controls="['calendar', 'timegrid']"
      :selectMultiple="false"
      label="Date & Timegrid"
      placeholder="Please Select..."
      inputStyle="box"
      labelStyle="stacked"
    />
  </MbscPage>
</template>
