// angular/src/demos/eventcalendar/eventcalendar/month-week-view/month-week-view.ts
import { Component, OnInit } from '@angular/core';
import { setOptions, MbscEventcalendarOptions, MbscCalendarEvent /* localeImport */ } from '@mobiscroll/angular';
import { HttpClient } from '@angular/common/http';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'month-week-view',
  templateUrl: './month-week-view.html',
})
export class AppComponent implements OnInit {
  constructor(private http: HttpClient) {}

  myEvents: MbscCalendarEvent[] = [];

  oneWeekSettings: MbscEventcalendarOptions = {
    view: {
      calendar: { type: 'week' },
    },
  };

  twoWeekSettings: MbscEventcalendarOptions = {
    view: {
      calendar: { type: 'week', size: 2 },
    },
  };

  threeWeekSettings: MbscEventcalendarOptions = {
    view: {
      calendar: { type: 'week', size: 3 },
    },
  };

  ngOnInit(): void {
    this.http.jsonp<MbscCalendarEvent[]>('https://trial.mobiscroll.com/events/?vers=5', 'callback').subscribe((resp) => {
      this.myEvents = resp;
    });
  }
}

// vue-ts/src/demos/eventcalendar/eventcalendar/month-week-view/month-week-view.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import {
  MbscEventcalendar,
  setOptions,
  getJson,
  MbscPage /* localeImport */
} from '@mobiscroll/vue'
import type { MbscCalendarEvent, MbscEventcalendarView } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref<MbscCalendarEvent[]>([])
const oneWeekView: MbscEventcalendarView = { calendar: { type: 'week' } }
const twoWeekView: MbscEventcalendarView = { calendar: { type: 'week', size: 2 } }
const threeWeekView: MbscEventcalendarView = { calendar: { type: 'week', size: 3 } }

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events: MbscCalendarEvent[]) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <MbscPage>
    <div class="mbsc-grid">
      <div class="mbsc-row">
        <div class="mbsc-col-sm-12 mbsc-col-md-4">
          <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">One week view</div>
            <MbscEventcalendar :drag="drag" :data="myEvents" :view="oneWeekView" />
          </div>
        </div>
        <div class="mbsc-col-sm-12 mbsc-col-md-4">
          <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">Two week view</div>
            <MbscEventcalendar :drag="drag" :data="myEvents" :view="twoWeekView" />
          </div>
        </div>
        <div class="mbsc-col-sm-12 mbsc-col-md-4">
          <div class="mbsc-form-group">
            <div class="mbsc-form-group-title">Three week view</div>
            <MbscEventcalendar :drag="drag" :data="myEvents" :view="threeWeekView" />
          </div>
        </div>
      </div>
    </div>
  </MbscPage>
</template>
