// react-ts/src/demos/range/range/calendar-scroller-dropdown/calendar-scroller-dropdown.tsx
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';
import React from 'react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => (
  <Page>
    <Datepicker
      controls={['calendar']}
      select="range"
      inputProps={{
        label: 'Calendar',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['date']}
      select="range"
      inputProps={{
        label: 'Date',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['datetime']}
      select="range"
      inputProps={{
        label: 'Date & Time',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['calendar', 'time']}
      select="range"
      inputProps={{
        label: 'Calendar & Time',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['time']}
      select="range"
      inputProps={{
        label: 'Time',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
  </Page>
);
export default App;

// mobiscroll-demos-vue/src/demos/datepicker/range/calendar-scroller-dropdown/calendar-scroller-dropdown.vue
<script setup>
import { MbscDatepicker, MbscPage, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscPage>
    <MbscDatepicker
      :controls="['calendar']"
      select="range"
      label="Calendar"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['date']"
      select="range"
      label="Date"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['datetime']"
      select="range"
      label="Date & Time"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['calendar', 'time']"
      select="range"
      label="Calendar & Time"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      select="range"
      label="Time"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
  </MbscPage>
</template>
