// mobiscroll-demos-vue/src/demos/eventcalendar/agenda/load-events-from-remote-api/load-events-from-remote-api.vue
<script setup>
import { getJson, MbscEventcalendar, setOptions /* localeImport */ } from '@mobiscroll/vue'
import { onMounted, ref } from 'vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([])

const myView = {
  agenda: { type: 'month' }
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <MbscEventcalendar :data="myEvents" :view="myView" />
</template>

// react/src/demos/eventcalendar/agenda/load-events-from-remote-api/load-events-from-remote-api.jsx
import React from 'react';
import { Eventcalendar, getJson /* localeImport */ } from '@mobiscroll/react';
import './load-events-from-remote-api.css';

function App() {
  const [myEvents, setEvents] = React.useState([]);

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  const view = React.useMemo(() => {
    return {
      agenda: { type: 'month' },
    };
  }, []);

  return (
    <Eventcalendar
      // theme
      // locale
      height={600}
      data={myEvents}
      view={view}
    />
  );
}

export default App;
