// vue/src/demos/forms/forms/alert-confirm-prompt/alert-confirm-prompt.vue
<script setup>
import { ref } from 'vue'
import {
  MbscAlert,
  MbscConfirm,
  MbscPrompt,
  MbscPage,
  MbscButton,
  setOptions /* localeImport */
} from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const isAlertOpen = ref(false)
const isConfirmOpen = ref(false)
const isPromptOpen = ref(false)
</script>

<template>
  <MbscPage>
    <MbscAlert
      title="Cellular Data is Turned Off for 'Safari'"
      message="You can turn on cellular data for this app in Settings."
      :isOpen="isAlertOpen"
      @close="isAlertOpen = true"
    />
    <MbscConfirm
      title="Use location service?"
      message="Help apps determine location. This means sending anonymous location data, even when no apps are running."
      okText="Agree"
      cancelText="Disagree"
      :isOpen="isConfirmOpen"
      @close="isConfirmOpen = true"
    />
    <MbscPrompt
      title="Sign in to iTunes Store"
      message="Enter the Apple ID password for 'hello@mobiscroll.com'."
      placeholder="placeholder"
      inputType="password"
      :isOpen="isPromptOpen"
      @close="isPromptOpen = true"
    />
    <MbscButton @click="isAlertOpen = true">Alert</MbscButton>
    <MbscButton @click="isConfirmOpen = true">Confirm</MbscButton>
    <MbscButton @click="isPromptOpen = true">Prompt</MbscButton>
  </MbscPage>
</template>

// react/src/demos/forms/forms/alert-confirm-prompt/alert-confirm-prompt.jsx
import React from 'react';
import { setOptions, Alert, Confirm, Prompt, Page, Button /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const [isAlertOpen, setAlertOpen] = React.useState(false);
  const [isConfirmOpen, setConfirmOpen] = React.useState(false);
  const [isPromptOpen, setPromptOpen] = React.useState(false);

  const showAlert = () => {
    setAlertOpen(true);
  };

  const closeAlert = React.useCallback(() => {
    setAlertOpen(false);
  }, []);

  const showConfirm = () => {
    setConfirmOpen(true);
  };

  const closeConfirm = React.useCallback(() => {
    setConfirmOpen(false);
  }, []);

  const showPrompt = () => {
    setPromptOpen(true);
  };

  const closePrompt = React.useCallback((value) => {
    setPromptOpen(false);
    console.log('The password is: ' + value);
  }, []);

  return (
    <Page>
      <Alert
        title='Cellular Data is Turned Off for "Safari"'
        message="You can turn on cellular data for this app in Settings."
        isOpen={isAlertOpen}
        onClose={closeAlert}
      />
      <Confirm
        title="Use location service?"
        message="Help apps determinde location. This means sending anonymous location data, even when no apps are running."
        okText="Agree"
        cancelText="Disagree"
        isOpen={isConfirmOpen}
        onClose={closeConfirm}
      />
      <Prompt
        title="Sign in to iTunes Store"
        message='Enter the Apple ID password for "hello@mobiscroll.com".'
        placeholder="Password"
        inputType="password"
        isOpen={isPromptOpen}
        onClose={closePrompt}
      />

      <Button onClick={showAlert}>Alert</Button>
      <Button onClick={showConfirm}>Confirm</Button>
      <Button onClick={showPrompt}>Prompt</Button>
    </Page>
  );
}

export default App;
