// vue-ts/src/demos/eventcalendar/eventcalendar/blocked-days-ranges/blocked-days-ranges.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import {
  MbscEventcalendar,
  setOptions,
  getJson,
  MbscToast /* localeImport */
} from '@mobiscroll/vue'
import type { MbscCalendarEvent } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref<MbscCalendarEvent[]>([])
const toastMessage = ref('')
const isToastOpen = ref(false)
const myView = {
  calendar: { labels: true }
}
const myInvalid = [
  {
    recurring: {
      repeat: 'weekly',
      weekDays: 'SA,SU'
    }
  },
  {
    allDay: true,
    start: 'dyndatetime(y,m,19)',
    end: 'dyndatetime(y,m,20)'
  },
  {
    allDay: true,
    start: 'dyndatetime(y,m,26)',
    end: 'dyndatetime(y,m,27)'
  }
]

function handleEventCreateFailed() {
  toastMessage.value = "Can't create event on this date"
  isToastOpen.value = true
}

function handleEventUpdateFailed() {
  toastMessage.value = "Can't add event on this date"
  isToastOpen.value = true
}

function handleToastClose() {
  isToastOpen.value = false
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/work-events/',
    (events: MbscCalendarEvent[]) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <MbscEventcalendar
    :data="myEvents"
    :view="myView"
    :invalid="myInvalid"
    :dragToCreate="true"
    :dragToMove="true"
    :dragToResize="true"
    invalidateEvent="strict"
    @event-create-failed="handleEventCreateFailed"
    @event-update-failed="handleEventUpdateFailed"
  />
  <MbscToast :message="toastMessage" :isOpen="isToastOpen" @close="handleToastClose" />
</template>

// react-ts/src/demos/eventcalendar/eventcalendar/blocked-days-ranges/blocked-days-ranges.tsx
import { Eventcalendar, getJson, Toast, MbscCalendarEvent, setOptions /* localeImport */ } from '@mobiscroll/react';
import React from 'react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => {
  const [isToastOpen, setToastOpen] = React.useState<boolean>(false);
  const [toastText, setToastText] = React.useState<string>();
  const [myEvents, setEvents] = React.useState<MbscCalendarEvent[]>([]);
  const inv = [
    {
      recurring: {
        repeat: 'weekly',
        weekDays: 'SA,SU',
      },
    },
    {
      allDay: true,
      start: 'dyndatetime(y,m,19)',
      end: 'dyndatetime(y,m,20)',
    },
    {
      allDay: true,
      start: 'dyndatetime(y,m,26)',
      end: 'dyndatetime(y,m,27)',
    },
  ];

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/work-events/',
      (events: MbscCalendarEvent[]) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  const view = React.useMemo(
    () => ({
      calendar: {
        labels: true,
      },
    }),
    [],
  );

  const onEventCreateFailed = React.useCallback(() => {
    setToastText("Can't create event on this date");
    setToastOpen(true);
  }, []);

  const onEventUpdateFailed = React.useCallback(() => {
    setToastText("Can't add event on this date");
    setToastOpen(true);
  }, []);

  const closeToast = React.useCallback(() => {
    setToastOpen(false);
  }, []);

  return (
    <div>
      <Eventcalendar
        data={myEvents}
        view={view}
        dragToCreate={true}
        dragToMove={true}
        dragToResize={true}
        invalidateEvent="strict"
        invalid={inv}
        onEventCreateFailed={onEventCreateFailed}
        onEventUpdateFailed={onEventUpdateFailed}
      />
      <Toast
        // theme
        message={toastText}
        isOpen={isToastOpen}
        onClose={closeToast}
      />
    </div>
  );
};
export default App;
