// mobiscroll-demos-vue/src/demos/eventcalendar/scheduler/customizing-header/customizing-header.vue
<script setup>
import {
  getJson,
  MbscButton,
  MbscCalendarNav,
  MbscCalendarToday,
  MbscEventcalendar,
  MbscSegmented,
  MbscSegmentedGroup,
  setOptions /* localeImport */
} from '@mobiscroll/vue'
import { onMounted, ref } from 'vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([])
const currentDate = ref(new Date())
const view = ref('schedule')
const calView = ref({
  schedule: { type: 'week' }
})

function getFirstDayOfWeek(d, prev) {
  const day = d.getDay()
  const diff = d.getDate() - day + (prev ? -7 : 7)
  return new Date(d.setDate(diff))
}

function navigatePage(prev) {
  const newCurrentDate = currentDate.value
  if (view.value === 'calendar') {
    const prevNextPage = new Date(
      newCurrentDate.getFullYear(),
      newCurrentDate.getMonth() + (prev ? -1 : 1),
      1
    )
    currentDate.value = prevNextPage
  } else {
    const prevNextSunday = getFirstDayOfWeek(newCurrentDate, prev)
    currentDate.value = prevNextSunday
  }
}

function changeView() {
  switch (view.value) {
    case 'calendar':
      calView.value = {
        calendar: { labels: true }
      }
      break
    case 'schedule':
      calView.value = {
        schedule: { type: 'week' }
      }
      break
  }
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <MbscEventcalendar
    :data="myEvents"
    :view="calView"
    :selectedDate="currentDate"
    className="md-custom-header"
  >
    <template #header>
      <MbscCalendarNav className="md-custom-header-nav"></MbscCalendarNav>
      <div class="md-custom-header-controls">
        <MbscButton
          @click="navigatePage(true)"
          icon="material-arrow-back"
          variant="flat"
          className="md-custom-header-button"
        ></MbscButton>
        <MbscCalendarToday className="md-custom-header-today"></MbscCalendarToday>
        <MbscButton
          @click="navigatePage(false)"
          icon="material-arrow-forward"
          variant="flat"
          className="md-custom-header-button"
        ></MbscButton>
      </div>
      <div class="md-custom-header-view">
        <MbscSegmentedGroup v-model="view" @change="changeView()">
          <MbscSegmented value="schedule" v-model="view" icon="material-list"></MbscSegmented>
          <MbscSegmented value="calendar" v-model="view" icon="calendar"></MbscSegmented>
        </MbscSegmentedGroup>
      </div>
    </template>
  </MbscEventcalendar>
</template>

<style>
.md-custom-header-controls {
  display: flex;
  flex: 1 0 auto;
  justify-content: center;
  align-items: center;
}

.md-custom-header-nav,
.md-custom-header-view {
  width: 180px;
}

.md-custom-header-button.mbsc-button {
  font-size: 20px;
  height: auto;
  padding: 0;
  margin: 0;
}

.md-custom-header .mbsc-segmented {
  width: 110px;
  float: right;
  margin-top: 0;
  margin-bottom: 0;
}

.md-custom-header .mbsc-material.mbsc-segmented,
.md-custom-header .mbsc-windows.mbsc-segmented {
  padding: 0;
}

.md-custom-header .mbsc-segmented .mbsc-segmented-button {
  font-size: 20px;
  height: 32px;
  padding: 0;
}
</style>

// react/src/demos/eventcalendar/eventcalendar/customizing-header/customizing-header.jsx
import {
  Button,
  CalendarNav,
  CalendarToday,
  getJson,
  Eventcalendar,
  Segmented,
  SegmentedGroup,
  setOptions /* localeImport */,
} from '@mobiscroll/react';
import { useCallback, useEffect, useState } from 'react';
import './customizing-header.css';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const [view, setView] = useState('calendar');
  const [myEvents, setEvents] = useState([]);
  const [currentDate, setCurrentDate] = useState(new Date());
  const [calView, setCalView] = useState({ calendar: { labels: true } });

  const changeView = useCallback((event) => {
    let calendarView;
    switch (event.target.value) {
      case 'calendar':
        calendarView = {
          calendar: {
            labels: true,
          },
        };
        break;
      case 'schedule':
        calendarView = {
          schedule: {
            type: 'week',
          },
        };
        break;
    }
    setView(event.target.value);
    setCalView(calendarView);
  }, []);

  const handleSelectedDateChange = useCallback((event) => {
    setCurrentDate(event.date);
  }, []);

  const getFirstDayOfWeek = useCallback((d, prev) => {
    const day = d.getDay();
    const diff = d.getDate() - day + (prev ? -7 : 7);
    return new Date(d.setDate(diff));
  }, []);

  const navigatePage = useCallback(
    (prev) => {
      if (view == 'calendar') {
        const prevNextPage = new Date(currentDate.getFullYear(), currentDate.getMonth() + (prev ? -1 : 1), 1);
        setCurrentDate(prevNextPage);
      } else {
        const prevNextSunday = getFirstDayOfWeek(currentDate, prev);
        setCurrentDate(prevNextSunday);
      }
    },
    [view, currentDate, getFirstDayOfWeek],
  );

  const customWithNavButtons = useCallback(
    () => (
      <>
        <CalendarNav className="md-custom-header-nav" />
        <div className="md-custom-header-controls">
          <Button onClick={() => navigatePage(true)} icon="material-arrow-back" variant="flat" className="md-custom-header-button"></Button>
          <CalendarToday className="md-custom-header-today" />
          <Button
            onClick={() => navigatePage(false)}
            icon="material-arrow-forward"
            variant="flat"
            className="md-custom-header-button"
          ></Button>
        </div>
        <div className="md-custom-header-view">
          <SegmentedGroup value={view} onChange={changeView}>
            <Segmented value="calendar" icon="calendar" />
            <Segmented value="schedule" icon="material-list" />
          </SegmentedGroup>
        </div>
      </>
    ),
    [changeView, navigatePage, view],
  );

  useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  return (
    <Eventcalendar
      cssClass="md-custom-header"
      onSelectedDateChange={handleSelectedDateChange}
      selectedDate={currentDate}
      renderHeader={customWithNavButtons}
      view={calView}
      data={myEvents}
    />
  );
}

export default App;
