// vue-ts/src/demos/calendar/calendar/appointment-booking/appointment-booking.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MbscDatepicker, MbscPage, getJson, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})

const multiple = ['dyndatetime(y,m,11)', 'dyndatetime(y,m,16)', 'dyndatetime(y,m,17)']
const minDate = 'dyndatetime(y,m,d)'
const maxDate = 'dyndatetime(y,m+6,d)'
const singleLabels = ref([])
const singleInvalid = ref([])
const datetimeLabels = ref([])
const datetimeInvalid = ref([])
const multipleLabels = ref([])
const multipleInvalid = ref([])

function handlePageLoadingSingle(event: any) {
  getPrices(event.firstDay, (bookings: any) => {
    singleLabels.value = bookings.labels
    singleInvalid.value = bookings.invalid
  })
}

function handlePageLoadingDatetime(event: any) {
  getDatetimes(event.firstDay, (bookings: any) => {
    datetimeLabels.value = bookings.labels
    datetimeInvalid.value = bookings.invalid
  })
}

function handlePageLoadingMultiple(event: any) {
  getBookings(event.firstDay, (bookings: any) => {
    multipleLabels.value = bookings.labels
    multipleInvalid.value = bookings.invalid
  })
}

function getPrices(d: Date, callback: any) {
  let invalid: any[] = []
  let labels: any[] = []

  getJson(
    'https://trial.mobiscroll.com/getprices/?year=' + d.getFullYear() + '&month=' + d.getMonth(),
    (bookings) => {
      for (let i = 0; i < bookings.length; ++i) {
        const booking = bookings[i]
        const d = new Date(booking.d)

        if (booking.price > 0) {
          labels.push({
            start: d,
            title: '$' + booking.price,
            textColor: '#e1528f'
          })
        } else {
          invalid.push(d)
        }
      }
      callback({ labels: labels, invalid: invalid })
    },
    'jsonp'
  )
}

function getDatetimes(d: Date, callback: any) {
  let invalid: any[] = []
  let labels: any[] = []

  getJson(
    'https://trial.mobiscroll.com/getbookingtime/?year=' +
      d.getFullYear() +
      '&month=' +
      d.getMonth(),
    (bookings) => {
      for (let i = 0; i < bookings.length; ++i) {
        const booking = bookings[i]
        const bDate = new Date(booking.d)

        if (booking.nr > 0) {
          labels.push({
            start: bDate,
            title: booking.nr + ' SPOTS',
            textColor: '#e1528f'
          })
          invalid = [...invalid, ...booking.invalid]
        } else {
          invalid.push(d)
        }
      }
      callback({ labels: labels, invalid: invalid })
    },
    'jsonp'
  )
}

function getBookings(d: Date, callback: any) {
  let invalid: any[] = []
  let labels: any[] = []

  getJson(
    'https://trial.mobiscroll.com/getbookings/?year=' + d.getFullYear() + '&month=' + d.getMonth(),
    (bookings) => {
      for (let i = 0; i < bookings.length; ++i) {
        const booking = bookings[i]
        const d = new Date(booking.d)

        if (booking.nr > 0) {
          labels.push({
            start: d,
            title: booking.nr + ' SPOTS',
            textColor: '#e1528f'
          })
        } else {
          invalid.push(d)
        }
      }
      callback({ labels: labels, invalid: invalid })
    },
    'jsonp'
  )
}
</script>

<template>
  <MbscPage>
    <div class="dms-calendar-booking">
      <div class="mbsc-form-group">
        <div class="mbsc-form-group-title">Single date & appointment booking</div>
        <MbscDatepicker
          display="inline"
          pages="auto"
          :controls="['calendar']"
          :min="minDate"
          :max="maxDate"
          :labels="singleLabels"
          :invalid="singleInvalid"
          @page-loading="handlePageLoadingSingle"
        />
      </div>
      <div class="mbsc-form-group">
        <div class="mbsc-form-group-title">Select date & time</div>
        <MbscDatepicker
          display="inline"
          minTime="08:00"
          maxTime="19:59"
          cssClass="booking-datetime"
          :controls="['calendar', 'timegrid']"
          :min="minDate"
          :max="maxDate"
          :stepMinute="60"
          :width="null"
          :labels="datetimeLabels"
          :invalid="datetimeInvalid"
          @page-loading="handlePageLoadingDatetime"
        />
      </div>
      <div class="mbsc-form-group">
        <div class="mbsc-form-group-title">Booking multiple appointments</div>
        <MbscDatepicker
          display="inline"
          pages="auto"
          cssClass="booking-datetime"
          v-model="multiple"
          :controls="['calendar']"
          :min="minDate"
          :max="maxDate"
          :stepMinute="60"
          :selectMultiple="true"
          :labels="multipleLabels"
          :invalid="multipleInvalid"
          @page-loading="handlePageLoadingMultiple"
        />
      </div>
    </div>
  </MbscPage>
</template>

<style>
.md-calendar-booking .mbsc-calendar-text {
  text-align: center;
}

.md-calendar-booking .booking-datetime .mbsc-datepicker-tab-calendar {
  flex: 1 1 0;
  min-width: 300px;
}

.md-calendar-booking .mbsc-timegrid-item {
  margin-top: 1.5em;
  margin-bottom: 1.5em;
}

.md-calendar-booking .mbsc-timegrid-container {
  top: 30px;
}
</style>

// react/src/demos/calendar/calendar/appointment-booking/appointment-booking.jsx
import React from 'react';
import { Datepicker, Page, getJson, setOptions /* localeImport */ } from '@mobiscroll/react';
import './appointment-booking.css';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const [multiple, setMultiple] = React.useState(['dyndatetime(y,m,11)', 'dyndatetime(y,m,16)', 'dyndatetime(y,m,17)']);
  const min = 'dyndatetime(y,m,d)';
  const max = 'dyndatetime(y,m+6,d)';
  const [singleLabels, setSingleLabels] = React.useState([]);
  const [singleInvalid, setSingleInvalid] = React.useState([]);
  const [datetimeLabels, setDatetimeLabels] = React.useState([]);
  const [datetimeInvalid, setDatetimeInvalid] = React.useState([]);
  const [multipleLabels, setMultipleLabels] = React.useState([]);
  const [multipleInvalid, setMultipleInvalid] = React.useState([]);

  const onPageLoadingSingle = React.useCallback((event, inst) => {
    getPrices(event.firstDay, (bookings) => {
      setSingleLabels(bookings.labels);
      setSingleInvalid(bookings.invalid);
    });
  }, []);

  const onPageLoadingDatetime = React.useCallback((event, inst) => {
    getDatetimes(event.firstDay, (bookings) => {
      setDatetimeLabels(bookings.labels);
      setDatetimeInvalid(bookings.invalid);
    });
  }, []);

  const onPageLoadingMultiple = React.useCallback((event, inst) => {
    getBookings(event.firstDay, (bookings) => {
      setMultipleLabels(bookings.labels);
      setMultipleInvalid(bookings.invalid);
    });
  }, []);

  const getPrices = (d, callback) => {
    let invalid = [];
    let labels = [];

    getJson(
      'https://trial.mobiscroll.com/getprices/?year=' + d.getFullYear() + '&month=' + d.getMonth(),
      (bookings) => {
        for (let i = 0; i < bookings.length; ++i) {
          const booking = bookings[i];
          const d = new Date(booking.d);

          if (booking.price > 0) {
            labels.push({
              start: d,
              title: '$' + booking.price,
              textColor: '#e1528f',
            });
          } else {
            invalid.push(d);
          }
        }
        callback({ labels: labels, invalid: invalid });
      },
      'jsonp',
    );
  };

  const getDatetimes = (d, callback) => {
    let invalid = [];
    let labels = [];

    getJson(
      'https://trial.mobiscroll.com/getbookingtime/?year=' + d.getFullYear() + '&month=' + d.getMonth(),
      (bookings) => {
        for (let i = 0; i < bookings.length; ++i) {
          const booking = bookings[i];
          const bDate = new Date(booking.d);

          if (booking.nr > 0) {
            labels.push({
              start: bDate,
              title: booking.nr + ' SPOTS',
              textColor: '#e1528f',
            });
            invalid = [...invalid, ...booking.invalid];
          } else {
            invalid.push(d);
          }
        }
        callback({ labels: labels, invalid: invalid });
      },
      'jsonp',
    );
  };

  const getBookings = (d, callback) => {
    let invalid = [];
    let labels = [];

    getJson(
      'https://trial.mobiscroll.com/getbookings/?year=' + d.getFullYear() + '&month=' + d.getMonth(),
      (bookings) => {
        for (let i = 0; i < bookings.length; ++i) {
          const booking = bookings[i];
          const d = new Date(booking.d);

          if (booking.nr > 0) {
            labels.push({
              start: d,
              title: booking.nr + ' SPOTS',
              textColor: '#e1528f',
            });
          } else {
            invalid.push(d);
          }
        }
        callback({ labels: labels, invalid: invalid });
      },
      'jsonp',
    );
  };

  return (
    <Page className="md-calendar-booking">
      <div className="mbsc-form-group">
        <div className="mbsc-form-group-title">Single date & appointment booking</div>
        <Datepicker
          display="inline"
          controls={['calendar']}
          min={min}
          max={max}
          labels={singleLabels}
          invalid={singleInvalid}
          pages="auto"
          onPageLoading={onPageLoadingSingle}
        />
      </div>
      <div className="mbsc-form-group">
        <div className="mbsc-form-group-title">Select date & time</div>
        <Datepicker
          display="inline"
          controls={['calendar', 'timegrid']}
          min={min}
          max={max}
          minTime="08:00"
          maxTime="19:59"
          stepMinute={60}
          width={null}
          labels={datetimeLabels}
          invalid={datetimeInvalid}
          onPageLoading={onPageLoadingDatetime}
          cssClass="booking-datetime"
        />
      </div>
      <div className="mbsc-form-group">
        <div className="mbsc-form-group-title">Booking multiple appointments</div>
        <Datepicker
          display="inline"
          controls={['calendar']}
          value={multiple}
          min={min}
          max={max}
          labels={multipleLabels}
          invalid={multipleInvalid}
          pages="auto"
          selectMultiple={true}
          onPageLoading={onPageLoadingMultiple}
        />
      </div>
    </Page>
  );
}

export default App;
