// vue/src/demos/calendar/calendar/date-time-picker/date-time-picker.vue
<script setup>
import { MbscDatepicker, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscDatepicker :controls="['calendar', 'time']" display="inline" />
  <MbscDatepicker :controls="['calendar', 'timegrid']" display="inline" />
</template>

// react-ts/src/demos/calendar/calendar/date-time-picker/date-time-picker.tsx
import React from 'react';
import { Datepicker, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => {
  return (
    <div>
      <Datepicker controls={['calendar', 'time']} display="inline" />
      <Datepicker controls={['calendar', 'timegrid']} display="inline" />
    </div>
  );
};
