// react/src/demos/eventcalendar/agenda/synchronized-views/synchronized-views.jsx
import React from 'react';
import { Eventcalendar, getJson, setOptions /* localeImport */ } from '@mobiscroll/react';
import './synchronized-views.css';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const [mySelectedDate, setSelectedDate] = React.useState(new Date());
  const [myEvents, setEvents] = React.useState([]);

  React.useEffect(() => {
    getJson(
      'https://trial.mobiscroll.com/events/?vers=5',
      (events) => {
        setEvents(events);
      },
      'jsonp',
    );
  }, []);

  const handleDateChange = React.useCallback((event, inst) => {
    setSelectedDate(event.date);
  }, []);

  const monthView = React.useMemo(() => {
    return {
      calendar: { popover: false, labels: false },
    };
  }, []);

  const dayView = React.useMemo(() => {
    return {
      agenda: { type: 'day' },
    };
  }, []);

  return (
    <div className="mbsc-grid md-demo-synchronized-views">
      <div className="mbsc-row mbsc-no-padding">
        <div className="mbsc-col-md-8 mbsc-col-12">
          <Eventcalendar view={monthView} data={myEvents} selectedDate={mySelectedDate} onSelectedDateChange={handleDateChange} />
        </div>
        <div className="mbsc-col-md-4 mbsc-col-12 md-col-right">
          <Eventcalendar view={dayView} data={myEvents} selectedDate={mySelectedDate} onSelectedDateChange={handleDateChange} />
        </div>
      </div>
    </div>
  );
}

export default App;

// mobiscroll-demos-vue/src/demos/eventcalendar/agenda/synchronized-views/synchronized-views.vue
<script setup>
import { getJson, MbscEventcalendar, setOptions /* localeImport */ } from '@mobiscroll/vue'
import { onMounted, ref } from 'vue'
import './synchronized-views.css'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([])
const mySelectedDate = ref(new Date())

const monthView = { calendar: { popover: false, labels: false } }
const dayView = { agenda: { type: 'day' } }

function handleDateChange(event) {
  mySelectedDate.value = event.date
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/events/?vers=5',
    (events) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template>
  <div className="mbsc-grid mds-sync-view">
    <div className="mbsc-row mbsc-no-padding">
      <div className="mbsc-col-12 mbsc-col-md-4 mbsc-col-xl-3">
        <MbscEventcalendar
          :data="myEvents"
          height="auto"
          :view="monthView"
          :selectedDate="mySelectedDate"
          @selected-date-change="handleDateChange"
        />
      </div>
      <div className="mds-sync-cal mbsc-col-12 mbsc-col-md-8 mbsc-col-xl-9">
        <MbscEventcalendar
          :data="myEvents"
          :selectedDate="mySelectedDate"
          :view="dayView"
          @selected-date-change="handleDateChange"
        />
      </div>
    </div>
  </div>
</template>
