// react-ts/src/demos/datetime/datetime/time-picker/time-picker.tsx
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';
import React from 'react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => (
  <Page>
    <Datepicker
      controls={['time']}
      inputProps={{
        label: 'Time picker',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['time']}
      timeFormat="HH:mm"
      inputProps={{
        label: '24 hour picker',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['time']}
      timeFormat="h:mm A"
      inputProps={{
        label: '12 h picker with AM/PM',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['time']}
      timeFormat="HH:mm:ss"
      headerText="Time: {value}"
      inputProps={{
        label: 'Hour, Min, Sec',
        labelStyle: 'stacked',
        inputStyle: 'outline',
        placeholder: 'Please Select...',
      }}
    />
  </Page>
);
export default App;

// mobiscroll-demos-vue/src/demos/datepicker/datetime/time-picker/time-picker.vue
<script setup>
import { MbscDatepicker, MbscPage, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscPage>
    <MbscDatepicker
      :controls="['time']"
      label="Time picker"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      timeFormat="HH:mm"
      label="24 hour picker"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      timeFormat="h:mm A"
      label="12 hour picker with AM/PM"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      timeFormat="HH:mm:ss"
      headerText="Time: {value}"
      label="Hour, Min, Sec"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
  </MbscPage>
</template>
