// react/src/demos/range/range/event-hooks/event-hooks.jsx
import React from 'react';
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  return (
    <Page>
      <Datepicker
        controls={['calendar']}
        select="range"
        inputProps={{
          label: 'Range',
          labelStyle: 'stacked',
          inputStyle: 'box',
          placeholder: 'Please Select...',
        }}
        onActiveDateChange={(event, inst) => {
          // Logic for the active date change
        }}
        onCancel={(event, inst) => {
          // Logic for cancel button click
        }}
        onCellClick={(event, inst) => {
          // Logic for event click
        }}
        onCellHoverIn={(event, inst) => {
          // Logic for handling cell hover in
        }}
        onCellHoverOut={(event, inst) => {
          // Logic for handling cell hover out
        }}
        onChange={(event, inst) => {
          // Logic for value change
        }}
        onClose={(event, inst) => {
          // Your custom event handler goes here
        }}
        onDestroy={(event, inst) => {
          // Your custom event handler goes here
        }}
        onInit={(event, inst) => {
          // Logic running on component init
        }}
        onLabelClick={(event, inst) => {
          // Logic for label click
        }}
        onOpen={(event, inst) => {
          // Your custom event handler goes here
        }}
        onPageChange={(event, inst) => {
          // Your custom event handler goes here
        }}
        onPageLoaded={(event, inst) => {
          // Use it to inject custom markup & attach custom listeners
        }}
        onPageLoading={(event, inst) => {
          // Use it to load data on demand
        }}
        onPosition={(event, inst) => {
          // Logic for component positioning
        }}
        onTempChange={(event, inst) => {
          // Logic for temporary value change
        }}
      />
    </Page>
  );
}

export default App;

// mobiscroll-demos-angular/src/demos/datepicker/calendar/event-hooks/event-hooks.ts
import { Component } from '@angular/core';
import { setOptions /* localeImport */ } from '@mobiscroll/angular';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'app-calendar-event-hooks',
  templateUrl: './event-hooks.html',
})
export class AppComponent {
  onCancel(): void {
    // Logic for cancel button click
  }

  onCellClick(): void {
    // Logic for event click
  }

  onCellHoverIn(): void {
    // Logic for handling cell hover in
  }

  onCellHoverOut(): void {
    // Logic for handling cell hover out
  }

  onChange(): void {
    // Logic for value change
  }

  onClose(): void {
    // Your custom event handler goes here
  }

  onDestroy(): void {
    // Your custom event handler goes here
  }

  onInit(): void {
    // Logic running on component init
  }

  onLabelClick(): void {
    // Logic for label click
  }

  onOpen(): void {
    // Your custom event handler goes here
  }

  onPageChange(): void {
    // Your custom event handler goes here
  }

  onPageLoaded(): void {
    // Use it to inject custom markup & attach custom listeners
  }

  onPageLoading(): void {
    // Use it to load data on demand
  }

  onPosition(): void {
    // Logic for component positioning
  }

  onTempChange(): void {
    // Logic for temporary value change
  }
}
