// vue/src/demos/datetime/datetime/single-select/single-select.vue
<script setup>
import { MbscDatepicker, MbscPage, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscPage>
    <MbscDatepicker
      :controls="['date']"
      :selectMultiple="false"
      label="Date"
      inputStyle="box"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      :selectMultiple="false"
      label="Time"
      inputStyle="box"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['date', 'time']"
      :selectMultiple="false"
      label="Date & Time"
      inputStyle="box"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
  </MbscPage>
</template>

// react-ts/src/demos/calendar/calendar/single-select/single-select.tsx
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';
import React from 'react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => (
  <Page>
    <Datepicker
      controls={['calendar']}
      selectMultiple={false}
      inputOptions={{
        label: 'Date',
        inputStyle: 'box',
        labelStyle: 'stacked',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['calendar', 'time']}
      selectMultiple={false}
      inputOptions={{
        label: 'Date & time',
        inputStyle: 'box',
        labelStyle: 'stacked',
        placeholder: 'Please Select...',
      }}
    />
    <Datepicker
      controls={['calendar', 'timegrid']}
      selectMultiple={false}
      inputOptions={{
        label: 'Date & timegrid',
        inputStyle: 'box',
        labelStyle: 'stacked',
        placeholder: 'Please Select...',
      }}
    />
  </Page>
);

export default App;
