// react-ts/src/demos/calendar/calendar/event-hooks/event-hooks.tsx
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';
import React from 'react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => (
  <Page>
    <Datepicker
      controls={['calendar']}
      inputProps={{
        label: 'Calendar',
        labelStyle: 'stacked',
        inputStyle: 'box',
        placeholder: 'Please Select...',
      }}
      onCancel={(event, inst) => {
        // Logic for cancel button click
      }}
      onCellClick={(event, inst) => {
        // Logic for event click
      }}
      handleCellHoverIn={(event, inst) => {
        // Logic for handling cell hover in
      }}
      handleCellHoverOut={(event, inst) => {
        // Logic for handling cell hover out
      }}
      onChange={(event, inst) => {
        // Logic for value change
      }}
      onClose={(event, inst) => {
        // Your custom event handler goes here
      }}
      onDestroy={(event, inst) => {
        // Your custom event handler goes here
      }}
      onInit={(event, inst) => {
        // Logic running on component init
      }}
      onLabelClick={(event, inst) => {
        // Logic for label click
      }}
      onOpen={(event, inst) => {
        // Your custom event handler goes here
      }}
      onPageChange={(event, inst) => {
        // Your custom event handler goes here
      }}
      onPageLoaded={(event, inst) => {
        // Use it to inject custom markup & attach custom listeners
      }}
      onPageLoading={(event, inst) => {
        // Use it to load data on demand
      }}
      onPosition={(event, inst) => {
        // Logic for component positioning
      }}
      onTempChange={(event, inst) => {
        // Logic for temporary value change
      }}
    />
  </Page>
);

export default App;

// angular/src/demos/calendar/calendar/event-hooks/event-hooks.ts
import { Component } from '@angular/core';
import { setOptions /* localeImport */ } from '@mobiscroll/angular';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'app-calendar-event-hooks',
  templateUrl: './event-hooks.html',
})
export class AppComponent {
  onCancel(event: any): void {
    // Logic for cancel button click
  }

  onCellClick(event: any): void {
    // Logic for event click
  }

  onCellHoverIn(event: any): void {
    // Logic for handling cell hover in
  }

  onCellHoverOut(event: any): void {
    // Logic for handling cell hover out
  }

  onChange(event: any): void {
    // Logic for value change
  }

  onClose(event: any): void {
    // Your custom event handler goes here
  }

  onDestroy(event: any): void {
    // Your custom event handler goes here
  }

  onInit(event: any): void {
    // Logic running on component init
  }

  onLabelClick(event: any): void {
    // Logic for label click
  }

  onOpen(event: any): void {
    // Your custom event handler goes here
  }

  onPageChange(event: any): void {
    // Your custom event handler goes here
  }

  onPageLoaded(event: any): void {
    // Use it to inject custom markup & attach custom listeners
  }

  onPageLoading(event: any): void {
    // Use it to load data on demand
  }

  onPosition(event: any): void {
    // Logic for component positioning
  }

  onTempChange(event: any): void {
    // Logic for temporary value change
  }
}
