// react/src/demos/datetime/datetime/date-object-ISO-8601-moment/date-object-ISO-8601-moment.jsx
import React from 'react';
import { Datepicker, Button, Page, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

function App() {
  const [obj, setObj] = React.useState();
  const objString = React.useMemo(() => (obj ? obj.toString() : null), [obj]);
  const [iso, setISO] = React.useState();
  const [momentJs, setMoment] = React.useState();
  const momentString = React.useMemo(() => (momentJs ? momentJs.toString() : null), [momentJs]);

  const setCustomObj = React.useCallback(() => {
    setObj(new Date(2020, 10, 15, 10, 45));
  });

  const objChange = React.useCallback((ev) => {
    setObj(ev.value);
  });

  const setCustomISO = React.useCallback(() => {
    setISO('2020-05-20T12:30:00');
  });

  const isoChange = React.useCallback((ev) => {
    setISO(ev.value);
  });

  const setCustomMoment = React.useCallback(() => {
    setMoment(moment([2020, 2, 6, 15, 30]));
  });

  const momentChange = React.useCallback((ev) => {
    setMoment(ev.value);
  });

  return (
    <Page>
      <div className="mbsc-form-group">
        <div className="mbsc-form-group-title">Working with Js Date Objects</div>
        <div className="mbsc-button-group-block">
          <Button onClick={setCustomObj}>Set: Sun Nov 15 2020 10:45:00 GMT</Button>
        </div>
        <Datepicker controls={['date']} value={obj} onChange={objChange} label="Date object" />
      </div>
      <div className="mbsc-padding">Return value: {objString}</div>

      <div className="mbsc-form-group">
        <div className="mbsc-form-group-title">Working with Date strings</div>
        <div className="mbsc-button-group-block">
          <Button onClick={setCustomISO}>Set: 2020-05-20T12:30:00</Button>
        </div>
        <Datepicker controls={['date']} returnFormat="iso8601" value={iso} onChange={isoChange} label="ISO string" />
      </div>
      <div className="mbsc-padding">Return value: {iso}</div>

      <div className="mbsc-form-group">
        <div className="mbsc-form-group-title">Working with Moment JS Objects</div>
        <div className="mbsc-button-group-block">
          <Button onClick={setCustomMoment}>Set: 2018-04-27T12:15:00+03:00</Button>
        </div>
        <Datepicker controls={['date']} returnFormat="moment" value={momentJs} onChange={momentChange} label="Moment JS" />
      </div>
      <div className="mbsc-padding">Return value: {momentString}</div>
    </Page>
  );
}

export default App;

// vue-ts/src/demos/calendar/calendar/date-object-ISO-8601-moment/date-object-ISO-8601-moment.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  MbscDatepicker,
  MbscPage,
  MbscButton,
  setOptions /* localeImport */
} from '@mobiscroll/vue'
import moment from 'moment'

setOptions({
  // locale,
  // theme
})

const date = ref<Date>()
const iso = ref<string>()
const momentJs = ref<any>()

function setDate() {
  date.value = new Date(2020, 10, 15, 10, 45)
}

function setISO() {
  iso.value = '2020-05-20T12:30:00'
}

function setMoment() {
  // make sure that moment js is loaded
  momentJs.value = moment([2020, 2, 6, 15, 30])
}
</script>

<template>
  <MbscPage>
    <div class="mbsc-form-group">
      <div class="mbsc-form-group-title">Controlling the default value</div>
      <div class="MbscButton-group-block">
        <MbscButton @click="setDate">Set: Sun Nov 15 2020 03:24:00 GMT</MbscButton>
      </div>
      <MbscDatepicker
        :controls="['calendar']"
        v-model="date"
        returnFormat="jsdate"
        label="Date object"
      />
    </div>
    <div class="mbsc-padding">Return value: {{ date }}</div>

    <div class="mbsc-form-group">
      <div class="mbsc-form-group-title">Working with Date strings</div>
      <div class="MbscButton-group-block">
        <MbscButton @click="setISO()">Set: 2020-05-20T12:30:00</MbscButton>
      </div>
      <div>
        <MbscDatepicker
          :controls="['calendar']"
          v-model="iso"
          returnFormat="iso8601"
          label="ISO string"
        />
      </div>
    </div>
    <div class="mbsc-padding">Return value: {{ iso }}</div>

    <div class="mbsc-form-group">
      <div class="mbsc-form-group-title">Working with Moment JS Objects</div>
      <div class="MbscButton-group-block">
        <MbscButton @click="setMoment()">Set: 2020-03-06T15:30:00+02:00</MbscButton>
      </div>
      <div>
        <MbscDatepicker
          :controls="['calendar']"
          v-model="momentJs"
          returnFormat="moment"
          label="Moment JS"
        />
      </div>
    </div>
    <div class="mbsc-padding">Return value: {{ momentJs ? momentJs.format() : '' }}</div>
  </MbscPage>
</template>
