// mobiscroll-demos-vue-ts/src/demos/eventcalendar/scheduler/event-drop-assign-attendees/event-drop-assign-attendees.vue
<script setup lang="ts">
import {
  MbscDraggable,
  MbscDropcontainer,
  MbscEventcalendar,
  MbscPage,
  MbscSnackbar,
  MbscToast,
  setOptions /* localeImport */
} from '@mobiscroll/vue'
import type { MbscEventcalendarView, MbscItemDragEvent } from '@mobiscroll/vue'
import { reactive, ref } from 'vue'
import { dyndatetime } from '../../../../dyndatetime'

setOptions({
  // locale,
  // theme
})

interface Attendee {
  id: string
  name: string
  avatar: string
  color: string
}

interface Meeting {
  id: string
  title: string
  start: string
  end: string
  resource: number
  color: string
  attendees: Attendee[]
}

const rooms = [
  { id: 1, name: 'Conference Room' },
  { id: 2, name: 'Board Room' },
  { id: 3, name: 'Meeting Room' },
  { id: 4, name: 'Training Room' }
]

const employees: Attendee[] = [
  { id: 'emp1', name: 'Alice Martin', avatar: 'AM', color: '#e74c3c' },
  { id: 'emp2', name: 'Bob Johnson', avatar: 'BJ', color: '#3498db' },
  { id: 'emp3', name: 'Carol Smith', avatar: 'CS', color: '#2ecc71' },
  { id: 'emp4', name: 'David Lee', avatar: 'DL', color: '#f39c12' },
  { id: 'emp5', name: 'Eva Chen', avatar: 'EC', color: '#9b59b6' },
  { id: 'emp6', name: 'Frank Diaz', avatar: 'FD', color: '#1abc9c' },
  { id: 'emp7', name: 'Grace Kim', avatar: 'GK', color: '#e67e22' },
  { id: 'emp8', name: 'Henry Patel', avatar: 'HP', color: '#34495e' },
  { id: 'emp9', name: 'Ivy Torres', avatar: 'IT', color: '#e84393' }
]

const meetings = ref<Meeting[]>([
  {
    id: 'evt1',
    title: 'Sprint Planning',
    start: dyndatetime('y,m,d,9'),
    end: dyndatetime('y,m,d,11'),
    resource: 1,
    color: '#b52db9',
    attendees: []
  },
  {
    id: 'evt2',
    title: 'Budget Review',
    start: dyndatetime('y,m,d,10'),
    end: dyndatetime('y,m,d,13'),
    resource: 2,
    color: '#669ce2',
    attendees: []
  },
  {
    id: 'evt3',
    title: 'Client Presentation',
    start: dyndatetime('y,m,d,15'),
    end: dyndatetime('y,m,d,18'),
    resource: 2,
    color: '#88bd42',
    attendees: []
  },
  {
    id: 'evt4',
    title: 'Project Kickoff',
    start: dyndatetime('y,m,d,9'),
    end: dyndatetime('y,m,d,11'),
    resource: 3,
    color: '#b6962f',
    attendees: []
  },
  {
    id: 'evt5',
    title: 'New Hire Orientation',
    start: dyndatetime('y,m,d,13'),
    end: dyndatetime('y,m,d,16'),
    resource: 4,
    color: '#c864f0',
    attendees: []
  },
  {
    id: 'evt6',
    title: 'Design Review',
    start: dyndatetime('y,m,d,13'),
    end: dyndatetime('y,m,d,15'),
    resource: 1,
    color: '#c7682d',
    attendees: []
  },
  {
    id: 'evt7',
    title: 'Product Demo',
    start: dyndatetime('y,m,d+1,9'),
    end: dyndatetime('y,m,d+1,11'),
    resource: 1,
    color: '#ad2b6c',
    attendees: []
  },
  {
    id: 'evt8',
    title: 'Stakeholder Update',
    start: dyndatetime('y,m,d+1,10'),
    end: dyndatetime('y,m,d+1,12'),
    resource: 2,
    color: '#0f60ca',
    attendees: []
  },
  {
    id: 'evt9',
    title: 'Code Review',
    start: dyndatetime('y,m,d+1,10'),
    end: dyndatetime('y,m,d+1,12'),
    resource: 3,
    color: '#56a823',
    attendees: []
  },
  {
    id: 'evt10',
    title: 'Safety Training',
    start: dyndatetime('y,m,d+1,13'),
    end: dyndatetime('y,m,d+1,16'),
    resource: 4,
    color: '#aa36d8',
    attendees: []
  },
  {
    id: 'evt11',
    title: 'Retrospective',
    start: dyndatetime('y,m,d+2,9'),
    end: dyndatetime('y,m,d+2,11'),
    resource: 1,
    color: '#c45f20',
    attendees: []
  },
  {
    id: 'evt12',
    title: 'Board Briefing',
    start: dyndatetime('y,m,d+2,13'),
    end: dyndatetime('y,m,d+2,16'),
    resource: 2,
    color: '#1e58a5',
    attendees: []
  },
  {
    id: 'evt13',
    title: 'Marketing Sync',
    start: dyndatetime('y,m,d+2,10'),
    end: dyndatetime('y,m,d+2,12'),
    resource: 3,
    color: '#549e27',
    attendees: []
  },
  {
    id: 'evt14',
    title: 'API Workshop',
    start: dyndatetime('y,m,d+2,13'),
    end: dyndatetime('y,m,d+2,16'),
    resource: 4,
    color: '#7c1ca1',
    attendees: []
  },
  {
    id: 'evt15',
    title: 'Architecture Review',
    start: dyndatetime('y,m,d+3,9'),
    end: dyndatetime('y,m,d+3,11,30'),
    resource: 1,
    color: '#a7511c',
    attendees: []
  },
  {
    id: 'evt16',
    title: 'Quarterly Planning',
    start: dyndatetime('y,m,d+3,13'),
    end: dyndatetime('y,m,d+3,16'),
    resource: 2,
    color: '#13488d',
    attendees: []
  },
  {
    id: 'evt17',
    title: 'Hiring Debrief',
    start: dyndatetime('y,m,d+3,10'),
    end: dyndatetime('y,m,d+3,12'),
    resource: 3,
    color: '#51ac19',
    attendees: []
  }
])

const myView: MbscEventcalendarView = {
  scheduler: {
    type: 'week',
    startDay: 1,
    endDay: 5,
    startTime: '08:00',
    endTime: '18:00',
    timeCellStep: 30,
    timeLabelStep: 30,
    virtualScroll: false
  }
}

const isExternalDragging = ref(false)
const dropStateMap = reactive<{ [key: string]: string }>({})
const eventRefs = reactive<{ [key: string]: HTMLElement }>({})
const dragElements = ref<HTMLElement[]>([])

const toastMessage = ref('')
const toastColor = ref<'success' | 'danger'>('success')
const isToastOpen = ref(false)

const snackbarMessage = ref('')
const snackbarButton = ref<{ text: string; action: () => void } | undefined>(undefined)
const isSnackbarOpen = ref(false)

function getAssignmentCount(empId: string): number {
  let count = 0
  for (const m of meetings.value) {
    count += m.attendees.filter((a) => a.id === empId).length
  }
  return count
}

function findConflict(empId: string, targetEventId: string): Meeting | null {
  const target = meetings.value.find((m) => m.id === targetEventId)
  if (!target) return null
  const tStart = new Date(target.start).getTime()
  const tEnd = new Date(target.end).getTime()
  for (const m of meetings.value) {
    if (m.id === targetEventId || !m.attendees.some((a) => a.id === empId)) continue
    const mStart = new Date(m.start).getTime()
    const mEnd = new Date(m.end).getTime()
    if (mStart < tEnd && mEnd > tStart) return m
  }
  return null
}

function handleEventDrop(e: MbscItemDragEvent, eventId: string): void {
  const employee = e.data as Attendee
  const meetingIdx = meetings.value.findIndex((m) => m.id === eventId)
  if (meetingIdx === -1) return
  const meeting = meetings.value[meetingIdx]

  dropStateMap[eventId] = ''

  if (meeting.attendees.some((a) => a.id === employee.id)) {
    toastMessage.value = employee.name + ' is already assigned'
    toastColor.value = 'danger'
    isToastOpen.value = true
    return
  }

  const conflict = findConflict(employee.id, eventId)
  if (conflict) {
    toastMessage.value = employee.name + ' already has a ' + conflict.title + ' on this timeslot'
    toastColor.value = 'danger'
    isToastOpen.value = true
    return
  }

  meetings.value = meetings.value.map((m) =>
    m.id === eventId
      ? {
          ...m,
          attendees: [
            ...m.attendees,
            { id: employee.id, name: employee.name, avatar: employee.avatar, color: employee.color }
          ]
        }
      : m
  )

  toastMessage.value = employee.name + ' assigned to ' + meeting.title
  toastColor.value = 'success'
  isToastOpen.value = true
}

function handleEventDragEnter(e: MbscItemDragEvent, eventId: string): void {
  const emp = e.data as Attendee
  const meeting = meetings.value.find((m) => m.id === eventId)
  if (emp && meeting) {
    if (meeting.attendees.some((a) => a.id === emp.id) || findConflict(emp.id, eventId)) {
      dropStateMap[eventId] = 'conflict'
    } else {
      dropStateMap[eventId] = 'active'
    }
  } else {
    dropStateMap[eventId] = 'active'
  }
}

function handleEventDragLeave(eventId: string): void {
  dropStateMap[eventId] = ''
}

function removeAttendee(eventId: string, empId: string): void {
  const meetingIdx = meetings.value.findIndex((m) => m.id === eventId)
  if (meetingIdx === -1) return
  const meeting = meetings.value[meetingIdx]
  const idx = meeting.attendees.findIndex((a) => a.id === empId)
  if (idx === -1) return

  const removedAtt = meeting.attendees[idx]

  meetings.value = meetings.value.map((m) =>
    m.id === eventId
      ? { ...m, attendees: [...m.attendees.slice(0, idx), ...m.attendees.slice(idx + 1)] }
      : m
  )

  snackbarMessage.value = removedAtt.name + ' removed from ' + meeting.title
  snackbarButton.value = {
    text: 'Undo',
    action: () => {
      meetings.value = meetings.value.map((m) =>
        m.id === eventId
          ? {
              ...m,
              attendees: [...m.attendees.slice(0, idx), removedAtt, ...m.attendees.slice(idx)]
            }
          : m
      )
      isSnackbarOpen.value = false
      toastMessage.value = 'Assignment restored'
      toastColor.value = 'success'
      isToastOpen.value = true
    }
  }
  isSnackbarOpen.value = true
}

function handleEmployeePointerDown(): void {
  function onMove() {
    isExternalDragging.value = true
    document.removeEventListener('pointermove', onMove)
  }
  function onUp() {
    isExternalDragging.value = false
    document.removeEventListener('pointermove', onMove)
    document.removeEventListener('pointerup', onUp)
  }
  document.addEventListener('pointermove', onMove)
  document.addEventListener('pointerup', onUp)
}
</script>

<template>
  <MbscPage
    :cssClass="`mds-scheduler-event-drop-assign-attendees${
      isExternalDragging ? ' mds-external-dragging' : ''
    }`"
  >
    <div class="mbsc-grid mbsc-no-padding">
      <div class="mbsc-row">
        <div class="mbsc-col-sm-3 mbsc-flex-col mds-sidebar">
          <div class="mbsc-form-group-title">Team Members</div>
          <div class="mds-employee-list mbsc-flex">
            <div
              v-for="(emp, i) in employees"
              :key="emp.id"
              :ref="
                (el) => {
                  if (el) dragElements[i] = el as HTMLElement
                }
              "
              class="mds-employee-item mbsc-flex"
              @pointerdown="handleEmployeePointerDown"
            >
              <div class="mds-employee-avatar mbsc-flex" :style="{ background: emp.color }">
                {{ emp.avatar }}
              </div>
              <div class="mds-employee-info mbsc-flex">
                <div class="mds-employee-name">{{ emp.name }}</div>
                <div class="mds-employee-count">
                  {{
                    getAssignmentCount(emp.id) > 0
                      ? getAssignmentCount(emp.id) +
                        ' meeting' +
                        (getAssignmentCount(emp.id) > 1 ? 's' : '')
                      : 'No assignments'
                  }}
                </div>
              </div>
              <MbscDraggable :element="dragElements[i]" :dragData="emp" />
            </div>
          </div>
        </div>
        <div class="mbsc-col-sm-9 mds-calendar-wrapper">
          <MbscEventcalendar
            :view="myView"
            :data="meetings"
            :resources="rooms"
            :dragToCreate="false"
            :dragToMove="false"
            :dragToResize="false"
            :clickToCreate="false"
            :eventDelete="false"
            :showEventTooltip="false"
          >
            <template #schedulerEvent="data">
              <div
                :ref="
                  (el) => {
                    if (el) eventRefs[data.original.id] = el as HTMLElement
                  }
                "
                class="mds-custom-event mbsc-flex"
                :class="{
                  'mds-drop-active': dropStateMap[data.original.id] === 'active',
                  'mds-drop-conflict': dropStateMap[data.original.id] === 'conflict'
                }"
                :style="{ borderLeft: '4px solid ' + data.original.color }"
              >
                <MbscDropcontainer
                  :element="eventRefs[data.original.id]"
                  @item-drop="handleEventDrop($event, data.original.id)"
                  @item-drag-enter="handleEventDragEnter($event, data.original.id)"
                  @item-drag-leave="handleEventDragLeave(data.original.id)"
                >
                  <div class="mds-event-header mbsc-flex">
                    <div class="mds-event-title">{{ data.title }}</div>
                    <div class="mds-event-time">{{ data.start }} - {{ data.end }}</div>
                  </div>
                  <div
                    v-if="data.original.attendees && data.original.attendees.length > 0"
                    class="mds-event-attendees mbsc-flex"
                  >
                    <span
                      v-for="att in data.original.attendees"
                      :key="att.id"
                      class="mds-attendee-chip"
                      :style="{ background: att.color }"
                      :title="att.name + ' (click to remove)'"
                      @click.stop="removeAttendee(data.original.id, att.id)"
                    >
                      {{ att.avatar }}
                      <span class="mds-attendee-remove">&times;</span>
                    </span>
                  </div>
                  <div class="mds-event-drop-hint">Drop people to assign</div>
                </MbscDropcontainer>
              </div>
            </template>
          </MbscEventcalendar>
        </div>
      </div>
    </div>
    <MbscToast
      :message="toastMessage"
      :color="toastColor"
      :isOpen="isToastOpen"
      @close="isToastOpen = false"
    />
    <MbscSnackbar
      :message="snackbarMessage"
      :button="snackbarButton"
      :isOpen="isSnackbarOpen"
      @close="isSnackbarOpen = false"
    />
  </MbscPage>
</template>

<style>
.mds-scheduler-event-drop-assign-attendees,
.mds-scheduler-event-drop-assign-attendees .mbsc-grid,
.mds-scheduler-event-drop-assign-attendees .mbsc-row,
.mds-scheduler-event-drop-assign-attendees .mds-calendar-wrapper {
  height: 100%;
}
.mds-scheduler-event-drop-assign-attendees .mds-sidebar {
  overflow-y: auto;
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-list {
  padding: 8px;
  flex-direction: column;
  gap: 4px;
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-item {
  align-items: center;
  gap: 10px;
  padding: 10px 12px;
  border-radius: 10px;
  cursor: grab;
  user-select: none;
  background: rgba(128, 128, 128, 0.5);
  margin: 0 5px 5px 5px;
  touch-action: none;
  transition:
    background 0.15s,
    box-shadow 0.2s,
    transform 0.15s;
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-item:hover {
  background: rgba(128, 128, 128, 0.4);
  transform: translateY(-1px);
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-item:active {
  transform: translateY(0);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-avatar {
  width: 34px;
  height: 34px;
  border-radius: 50%;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 11px;
  font-weight: 700;
  flex-shrink: 0;
  letter-spacing: 0.5px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.15);
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-info {
  flex-direction: column;
  overflow: hidden;
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-name {
  font-size: 15px;
  font-weight: 500;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.mds-scheduler-event-drop-assign-attendees .mds-employee-count {
  font-size: 13px;
  opacity: 0.55;
}
.mds-scheduler-event-drop-assign-attendees .mds-calendar-wrapper {
  border-left: 1px solid rgba(0, 0, 0, 0.1);
}
/* Drag clone is appended to body, outside the root — keep unscoped */
.mds-employee-item.mbsc-drag-clone {
  opacity: 0.8;
}
.mds-scheduler-event-drop-assign-attendees .mds-custom-event {
  background: #cccccc;
  border-radius: 6px;
  padding: 6px;
  height: 100%;
  box-sizing: border-box;
  flex-direction: column;
  gap: 4px;
  overflow: hidden;
  outline: 2px solid transparent;
  transition: background 0.15s;
  position: relative;
}
.mds-scheduler-event-drop-assign-attendees .mds-event-header {
  flex-direction: column;
  gap: 1px;
}
.mds-scheduler-event-drop-assign-attendees .mds-event-title {
  font-size: 13px;
  font-weight: 600;
  color: #181818;
  overflow: hidden;
  text-overflow: ellipsis;
}
.mds-scheduler-event-drop-assign-attendees .mds-event-time {
  font-size: 11px;
  color: #545454;
}
.mds-scheduler-event-drop-assign-attendees .mds-event-attendees {
  flex-wrap: wrap;
  gap: 3px;
}
.mds-scheduler-event-drop-assign-attendees .mds-event-drop-hint {
  display: none;
  font-size: 11px;
  font-style: italic;
  color: #686868;
}
.mds-scheduler-event-drop-assign-attendees.mds-external-dragging .mds-event-drop-hint {
  display: block;
}
.mds-scheduler-event-drop-assign-attendees.mds-external-dragging .mds-custom-event {
  outline: 2px dashed #b9b9b9;
}
.mds-scheduler-event-drop-assign-attendees .mds-attendee-chip {
  display: flex;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  align-items: center;
  justify-content: center;
  color: #fff;
  font-size: 9px;
  font-weight: 700;
  border: 2px solid rgba(255, 255, 255, 0.5);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);
  cursor: pointer;
  position: relative;
}
.mds-scheduler-event-drop-assign-attendees .mds-attendee-remove {
  display: none;
  position: absolute;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  border-radius: 50%;
  align-items: center;
  justify-content: center;
  font-size: 10px;
  line-height: 1;
}
.mds-scheduler-event-drop-assign-attendees .mds-attendee-chip:hover .mds-attendee-remove {
  display: flex;
}
.mds-scheduler-event-drop-assign-attendees .mds-custom-event.mds-drop-active {
  cursor: copy;
  outline: 2px solid rgba(54, 133, 43, 0.8);
  background: rgba(180, 223, 173, 0.8);
}
.mds-scheduler-event-drop-assign-attendees .mds-custom-event.mds-drop-conflict {
  cursor: not-allowed;
  outline: 2px solid rgba(145, 34, 34, 0.8);
  background: rgba(235, 194, 194, 0.8);
}
.mds-scheduler-event-drop-assign-attendees .mbsc-scheduler-event {
  min-height: 80px;
}
.mds-scheduler-event-drop-assign-attendees .mbsc-schedule-event-inner {
  height: 100%;
}
</style>

// mobiscroll-demos-react-ts/src/demos/eventcalendar/scheduler/event-drop-assign-attendees/event-drop-assign-attendees.tsx
import {
  Draggable,
  Dropcontainer,
  Eventcalendar,
  MbscCalendarEvent,
  MbscCalendarEventData,
  MbscEventcalendarView,
  MbscItemDragEvent,
  Page,
  setOptions,
  Snackbar,
  Toast /* localeImport */,
} from '@mobiscroll/react';
import { FC, RefObject, useCallback, useMemo, useRef, useState } from 'react';
import { dyndatetime } from '../../../../dyndatetime';
import './event-drop-assign-attendees.css';

setOptions({
  // localeJs,
  // themeJs
});

interface Attendee {
  id: string;
  name: string;
  avatar: string;
  color: string;
}

interface Meeting extends MbscCalendarEvent {
  attendees: Attendee[];
}

const rooms = [
  { id: 1, name: 'Conference Room' },
  { id: 2, name: 'Board Room' },
  { id: 3, name: 'Meeting Room' },
  { id: 4, name: 'Training Room' },
];

const employees: Attendee[] = [
  { id: 'emp1', name: 'Alice Martin', avatar: 'AM', color: '#e74c3c' },
  { id: 'emp2', name: 'Bob Johnson', avatar: 'BJ', color: '#3498db' },
  { id: 'emp3', name: 'Carol Smith', avatar: 'CS', color: '#2ecc71' },
  { id: 'emp4', name: 'David Lee', avatar: 'DL', color: '#f39c12' },
  { id: 'emp5', name: 'Eva Chen', avatar: 'EC', color: '#9b59b6' },
  { id: 'emp6', name: 'Frank Diaz', avatar: 'FD', color: '#1abc9c' },
  { id: 'emp7', name: 'Grace Kim', avatar: 'GK', color: '#e67e22' },
  { id: 'emp8', name: 'Henry Patel', avatar: 'HP', color: '#34495e' },
  { id: 'emp9', name: 'Ivy Torres', avatar: 'IT', color: '#e84393' },
];

const initialMeetings: Meeting[] = [
  {
    id: 'evt1',
    title: 'Sprint Planning',
    start: dyndatetime('y,m,d,9'),
    end: dyndatetime('y,m,d,11'),
    resource: 1,
    color: '#b52db9',
    attendees: [],
  },
  {
    id: 'evt2',
    title: 'Budget Review',
    start: dyndatetime('y,m,d,10'),
    end: dyndatetime('y,m,d,13'),
    resource: 2,
    color: '#669ce2',
    attendees: [],
  },
  {
    id: 'evt3',
    title: 'Client Presentation',
    start: dyndatetime('y,m,d,15'),
    end: dyndatetime('y,m,d,18'),
    resource: 2,
    color: '#88bd42',
    attendees: [],
  },
  {
    id: 'evt4',
    title: 'Project Kickoff',
    start: dyndatetime('y,m,d,9'),
    end: dyndatetime('y,m,d,11'),
    resource: 3,
    color: '#b6962f',
    attendees: [],
  },
  {
    id: 'evt5',
    title: 'New Hire Orientation',
    start: dyndatetime('y,m,d,13'),
    end: dyndatetime('y,m,d,16'),
    resource: 4,
    color: '#c864f0',
    attendees: [],
  },
  {
    id: 'evt6',
    title: 'Design Review',
    start: dyndatetime('y,m,d,13'),
    end: dyndatetime('y,m,d,15'),
    resource: 1,
    color: '#c7682d',
    attendees: [],
  },
  {
    id: 'evt7',
    title: 'Product Demo',
    start: dyndatetime('y,m,d+1,9'),
    end: dyndatetime('y,m,d+1,11'),
    resource: 1,
    color: '#ad2b6c',
    attendees: [],
  },
  {
    id: 'evt8',
    title: 'Stakeholder Update',
    start: dyndatetime('y,m,d+1,10'),
    end: dyndatetime('y,m,d+1,12'),
    resource: 2,
    color: '#0f60ca',
    attendees: [],
  },
  {
    id: 'evt9',
    title: 'Code Review',
    start: dyndatetime('y,m,d+1,10'),
    end: dyndatetime('y,m,d+1,12'),
    resource: 3,
    color: '#56a823',
    attendees: [],
  },
  {
    id: 'evt10',
    title: 'Safety Training',
    start: dyndatetime('y,m,d+1,13'),
    end: dyndatetime('y,m,d+1,16'),
    resource: 4,
    color: '#aa36d8',
    attendees: [],
  },
  {
    id: 'evt11',
    title: 'Retrospective',
    start: dyndatetime('y,m,d+2,9'),
    end: dyndatetime('y,m,d+2,11'),
    resource: 1,
    color: '#c45f20',
    attendees: [],
  },
  {
    id: 'evt12',
    title: 'Board Briefing',
    start: dyndatetime('y,m,d+2,13'),
    end: dyndatetime('y,m,d+2,16'),
    resource: 2,
    color: '#1e58a5',
    attendees: [],
  },
  {
    id: 'evt13',
    title: 'Marketing Sync',
    start: dyndatetime('y,m,d+2,10'),
    end: dyndatetime('y,m,d+2,12'),
    resource: 3,
    color: '#549e27',
    attendees: [],
  },
  {
    id: 'evt14',
    title: 'API Workshop',
    start: dyndatetime('y,m,d+2,13'),
    end: dyndatetime('y,m,d+2,16'),
    resource: 4,
    color: '#7c1ca1',
    attendees: [],
  },
  {
    id: 'evt15',
    title: 'Architecture Review',
    start: dyndatetime('y,m,d+3,9'),
    end: dyndatetime('y,m,d+3,11,30'),
    resource: 1,
    color: '#a7511c',
    attendees: [],
  },
  {
    id: 'evt16',
    title: 'Quarterly Planning',
    start: dyndatetime('y,m,d+3,13'),
    end: dyndatetime('y,m,d+3,16'),
    resource: 2,
    color: '#13488d',
    attendees: [],
  },
  {
    id: 'evt17',
    title: 'Hiring Debrief',
    start: dyndatetime('y,m,d+3,10'),
    end: dyndatetime('y,m,d+3,12'),
    resource: 3,
    color: '#51ac19',
    attendees: [],
  },
];

interface EmployeeItemProps {
  employee: Attendee;
  count: number;
  onPointerDown: () => void;
}

function EmployeeItem({ employee, count, onPointerDown }: EmployeeItemProps) {
  const [el, setEl] = useState<HTMLDivElement | null>(null);

  return (
    <div ref={setEl} className="mds-employee-item mbsc-flex" id={'mds-emp-' + employee.id} onPointerDown={onPointerDown}>
      <div className="mds-employee-avatar mbsc-flex" style={{ background: employee.color }}>
        {employee.avatar}
      </div>
      <div className="mds-employee-info mbsc-flex">
        <div className="mds-employee-name">{employee.name}</div>
        <div className="mds-employee-count">{count > 0 ? count + ' meeting' + (count > 1 ? 's' : '') : 'No assignments'}</div>
      </div>
      <Draggable element={el} dragData={employee} />
    </div>
  );
}

interface SchedulerEventProps {
  data: MbscCalendarEventData;
  meetingsRef: RefObject<Meeting[]>;
  onDrop: (e: MbscItemDragEvent, eventId: string) => void;
  onFindConflict: (empId: string, targetEventId: string) => Meeting | null;
  onRemoveAttendee: (eventId: string, empId: string) => void;
}

function SchedulerEvent({ data, meetingsRef, onDrop, onFindConflict, onRemoveAttendee }: SchedulerEventProps) {
  const [containerEl, setContainerEl] = useState<HTMLDivElement | null>(null);
  const [dropClass, setDropClass] = useState('');
  const event = data.original as Meeting;
  const attendees: Attendee[] = event.attendees || [];

  const handleDrop = useCallback(
    (e: MbscItemDragEvent) => {
      setDropClass('');
      onDrop(e, event.id as string);
    },
    [onDrop, event.id],
  );

  const handleDragEnter = useCallback(
    (e: MbscItemDragEvent) => {
      const emp = e.data as Attendee;
      const meeting = meetingsRef.current.find((m) => m.id === event.id);
      if (!meeting) {
        setDropClass('mds-drop-active');
        return;
      }
      if (emp) {
        if (meeting.attendees.some((a) => a.id === emp.id) || onFindConflict(emp.id, event.id as string)) {
          setDropClass('mds-drop-conflict');
        } else {
          setDropClass('mds-drop-active');
        }
      } else {
        setDropClass('mds-drop-active');
      }
    },
    [event.id, meetingsRef, onFindConflict],
  );

  const handleDragLeave = useCallback(() => {
    setDropClass('');
  }, []);

  return (
    <div ref={setContainerEl} className={'mds-custom-event mbsc-flex ' + dropClass} style={{ borderLeft: '4px solid ' + event.color }}>
      <Dropcontainer element={containerEl} onItemDrop={handleDrop} onItemDragEnter={handleDragEnter} onItemDragLeave={handleDragLeave}>
        <div className="mds-event-header mbsc-flex">
          <div className="mds-event-title">{event.title as string}</div>
          <div className="mds-event-time">
            {data.start} - {data.end}
          </div>
        </div>
        {attendees.length > 0 && (
          <div className="mds-event-attendees mbsc-flex">
            {attendees.map((att) => (
              <span
                key={att.id}
                className="mds-attendee-chip"
                style={{ background: att.color }}
                title={att.name + ' (click to remove)'}
                onClick={(e) => {
                  e.stopPropagation();
                  onRemoveAttendee(event.id as string, att.id);
                }}
              >
                {att.avatar}
                <span className="mds-attendee-remove">&times;</span>
              </span>
            ))}
          </div>
        )}
        <div className="mds-event-drop-hint">Drop people to assign</div>
      </Dropcontainer>
    </div>
  );
}

const App: FC = () => {
  const meetingsRef = useRef<Meeting[]>(initialMeetings);
  const [myEvents, setMyEvents] = useState<Meeting[]>(initialMeetings);
  const [isExternalDragging, setIsExternalDragging] = useState(false);

  const [toastMessage, setToastMessage] = useState('');
  const [toastColor, setToastColor] = useState<'success' | 'danger'>('success');
  const [isToastOpen, setIsToastOpen] = useState(false);

  const [snackbarMessage, setSnackbarMessage] = useState('');
  const [snackbarButton, setSnackbarButton] = useState<{ text: string; action: () => void } | undefined>(undefined);
  const [isSnackbarOpen, setIsSnackbarOpen] = useState(false);

  const myView = useMemo<MbscEventcalendarView>(
    () => ({
      scheduler: {
        type: 'week',
        startDay: 1,
        endDay: 5,
        startTime: '08:00',
        endTime: '18:00',
        timeCellStep: 30,
        timeLabelStep: 30,
        virtualScroll: false,
      },
    }),
    [],
  );

  const getAssignmentCount = useCallback(
    (empId: string): number => myEvents.filter((m) => m.attendees.some((a) => a.id === empId)).length,
    [myEvents],
  );

  const findConflict = useCallback((empId: string, targetEventId: string): Meeting | null => {
    const target = meetingsRef.current.find((m) => m.id === targetEventId);
    if (!target) return null;
    const tStart = new Date(target.start as string).getTime();
    const tEnd = new Date(target.end as string).getTime();
    for (const m of meetingsRef.current) {
      if (m.id === targetEventId || !m.attendees.some((a) => a.id === empId)) continue;
      const mStart = new Date(m.start as string).getTime();
      const mEnd = new Date(m.end as string).getTime();
      if (mStart < tEnd && mEnd > tStart) return m;
    }
    return null;
  }, []);

  const handleDrop = useCallback(
    (dropEvent: MbscItemDragEvent, eventId: string) => {
      const employee = dropEvent.data as Attendee;
      const meetingIdx = meetingsRef.current.findIndex((m) => m.id === eventId);
      if (meetingIdx === -1) return;
      const meeting = meetingsRef.current[meetingIdx];

      if (meeting.attendees.some((a) => a.id === employee.id)) {
        setToastMessage(employee.name + ' is already assigned');
        setToastColor('danger');
        setIsToastOpen(true);
        return;
      }

      const conflict = findConflict(employee.id, eventId);
      if (conflict) {
        setToastMessage(employee.name + ' already has a ' + conflict.title + ' on this timeslot');
        setToastColor('danger');
        setIsToastOpen(true);
        return;
      }

      const updatedMeeting: Meeting = {
        ...meeting,
        attendees: [...meeting.attendees, { id: employee.id, name: employee.name, avatar: employee.avatar, color: employee.color }],
      };
      meetingsRef.current = [...meetingsRef.current.slice(0, meetingIdx), updatedMeeting, ...meetingsRef.current.slice(meetingIdx + 1)];
      setMyEvents(meetingsRef.current);

      setToastMessage(employee.name + ' assigned to ' + (meeting.title as string));
      setToastColor('success');
      setIsToastOpen(true);
    },
    [findConflict],
  );

  const handleRemoveAttendee = useCallback((eventId: string, empId: string) => {
    const meetingIdx = meetingsRef.current.findIndex((m) => m.id === eventId);
    if (meetingIdx === -1) return;
    const meeting = meetingsRef.current[meetingIdx];
    const idx = meeting.attendees.findIndex((a) => a.id === empId);
    if (idx === -1) return;

    const removedAtt = meeting.attendees[idx];
    const updatedMeeting: Meeting = {
      ...meeting,
      attendees: [...meeting.attendees.slice(0, idx), ...meeting.attendees.slice(idx + 1)],
    };
    meetingsRef.current = [...meetingsRef.current.slice(0, meetingIdx), updatedMeeting, ...meetingsRef.current.slice(meetingIdx + 1)];
    setMyEvents(meetingsRef.current);

    setSnackbarMessage(removedAtt.name + ' removed from ' + (meeting.title as string));
    setSnackbarButton({
      text: 'Undo',
      action: () => {
        const mIdx = meetingsRef.current.findIndex((m) => m.id === eventId);
        if (mIdx === -1) return;
        const m = meetingsRef.current[mIdx];
        const restored: Meeting = { ...m, attendees: [...m.attendees.slice(0, idx), removedAtt, ...m.attendees.slice(idx)] };
        meetingsRef.current = [...meetingsRef.current.slice(0, mIdx), restored, ...meetingsRef.current.slice(mIdx + 1)];
        setMyEvents(meetingsRef.current);
        setIsSnackbarOpen(false);
        setToastMessage('Assignment restored');
        setToastColor('success');
        setIsToastOpen(true);
      },
    });
    setIsSnackbarOpen(true);
  }, []);

  const handleEmployeePointerDown = useCallback(() => {
    const onMove = () => {
      setIsExternalDragging(true);
      document.removeEventListener('pointermove', onMove);
    };
    const onUp = () => {
      setIsExternalDragging(false);
      document.removeEventListener('pointermove', onMove);
      document.removeEventListener('pointerup', onUp);
    };
    document.addEventListener('pointermove', onMove);
    document.addEventListener('pointerup', onUp);
  }, []);

  const renderSchedulerEvent = useCallback(
    (data: MbscCalendarEventData) => (
      <SchedulerEvent
        data={data}
        meetingsRef={meetingsRef}
        onDrop={handleDrop}
        onFindConflict={findConflict}
        onRemoveAttendee={handleRemoveAttendee}
      />
    ),
    [handleDrop, findConflict, handleRemoveAttendee],
  );

  return (
    <Page className={'mds-scheduler-event-drop-assign-attendees' + (isExternalDragging ? ' mds-external-dragging' : '')}>
      <div className="mbsc-grid mbsc-no-padding">
        <div className="mbsc-row">
          <div className="mbsc-col-sm-3 mbsc-flex-col mds-sidebar">
            <div className="mbsc-form-group-title">Team Members</div>
            <div className="mds-employee-list mbsc-flex">
              {employees.map((emp) => (
                <EmployeeItem key={emp.id} employee={emp} count={getAssignmentCount(emp.id)} onPointerDown={handleEmployeePointerDown} />
              ))}
            </div>
          </div>
          <div className="mbsc-col-sm-9 mds-calendar-wrapper">
            <Eventcalendar
              view={myView}
              data={myEvents}
              resources={rooms}
              dragToCreate={false}
              dragToMove={false}
              dragToResize={false}
              clickToCreate={false}
              eventDelete={false}
              showEventTooltip={false}
              renderSchedulerEvent={renderSchedulerEvent}
            />
          </div>
        </div>
      </div>
      <Toast message={toastMessage} color={toastColor} isOpen={isToastOpen} onClose={() => setIsToastOpen(false)} />
      <Snackbar message={snackbarMessage} button={snackbarButton} isOpen={isSnackbarOpen} onClose={() => setIsSnackbarOpen(false)} />
    </Page>
  );
};

export default App;
