// react-ts/src/demos/calendar/calendar/week-select/week-select.tsx
import React from 'react';
import { Datepicker /* localeImport */ } from '@mobiscroll/react';

const App: React.FC = () => {
  return (
    <mobiscroll.Datepicker
      // locale
      // theme
      controls={['calendar']}
      display="inline"
      select="preset-range"
      firstSelectDay={1}
      selectSize={14}
    />
  );
};
export default App;

// mobiscroll-demos-angular/src/demos/datepicker/calendar/week-select/week-select.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { MbscModule, setOptions /* localeImport */ } from '@mobiscroll/angular';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'app-calendar-week-select',
  templateUrl: './week-select.html',
  standalone: true,
  imports: [CommonModule, MbscModule],
})
export class AppComponent {}
