// vue/src/demos/eventcalendar/scheduler/show-hide-hours-days/show-hide-hours-days.vue
<script setup>
import { getJson, MbscEventcalendar, setOptions /* localeImport */ } from '@mobiscroll/vue'
import { onMounted, ref } from 'vue'

setOptions({
  // locale,
  // theme
})

const myEvents = ref([])

const myView = {
  schedule: {
    type: 'week',
    startDay: 1,
    endDay: 5,
    startTime: '09:00',
    endTime: '18:00',
    timeCellStep: 30,
    timeLabelStep: 30
  }
}

onMounted(() => {
  getJson(
    'https://trial.mobiscroll.com/workday-events/?vers=5',
    (events) => {
      myEvents.value = events
    },
    'jsonp'
  )
})
</script>

<template><MbscEventcalendar :drag="drag" :view="myView" :data="myEvents" /></template>

// angular/src/demos/eventcalendar/scheduler/show-hide-hours-days/show-hide-hours-days.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { MbscEventcalendarOptions, setOptions /* localeImport */ } from '@mobiscroll/angular';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'app-scheduler-show-hide-hours-days',
  templateUrl: './show-hide-hours-days.html',
})
export class AppComponent implements OnInit {
  constructor(private http: HttpClient) {}

  events: any;

  eventSettings: MbscEventcalendarOptions = {
    // drag,
    view: {
      schedule: {
        type: 'week',
        startDay: 1,
        endDay: 5,
        startTime: '09:00',
        endTime: '18:00',
        timeCellStep: 30,
        timeLabelStep: 30,
      },
    },
  };

  ngOnInit() {
    this.http.jsonp('https://trial.mobiscroll.com//workday-events/?vers=5', 'callback').subscribe((resp: any) => {
      this.events = resp;
    });
  }
}
