// react-ts/src/demos/datetime/datetime/time-value-steps/time-value-steps.tsx
import React from 'react';
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => {
  return (
    <Page>
      <Datepicker
        controls={['datetime']}
        stepMinute={15}
        inputProps={{
          label: 'Date & Time (every 15 min)',
          labelStyle: 'stacked',
          inputStyle: 'outline',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['time']}
        stepMinute={5}
        inputProps={{
          label: 'Time (every 5 min)',
          labelStyle: 'stacked',
          inputStyle: 'outline',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['time']}
        stepHour={2}
        inputProps={{
          label: 'Time (every 2 hours)',
          labelStyle: 'stacked',
          inputStyle: 'outline',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['time']}
        stepSecond={30}
        timeFormat="HH:mm:ss"
        inputProps={{
          label: 'Time (every 30 seconds)',
          labelStyle: 'stacked',
          inputStyle: 'outline',
          placeholder: 'Please Select...',
        }}
      />
    </Page>
  );
};

export default App;

// mobiscroll-demos-vue/src/demos/datepicker/datetime/time-value-steps/time-value-steps.vue
<script setup>
import { MbscDatepicker, MbscPage, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscPage>
    <MbscDatepicker
      :controls="['datetime']"
      :stepMinute="15"
      label="Date & Time (every 15 min)"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      :stepMinute="5"
      label="Time (every 5 min)"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      :stepHour="2"
      label="Time (every 2 hours)"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
    <MbscDatepicker
      :controls="['time']"
      :stepSecond="30"
      timeFormat="HH:mm:ss"
      label="Time (every 30 seconds)"
      inputStyle="outline"
      labelStyle="stacked"
      placeholder="Please Select..."
    />
  </MbscPage>
</template>
