// vue-ts/src/demos/calendar/calendar/single-select/single-select.vue
<script setup lang="ts">
import { ref } from 'vue'
import { MbscDatepicker, MbscPage, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscPage>
    <MbscDatepicker
      :controls="['calendar']"
      :selectMultiple="false"
      label="Date"
      placeholder="Please Select..."
      inputStyle="box"
      labelStyle="stacked"
    />
    <MbscDatepicker
      :controls="['calendar', 'time']"
      :selectMultiple="false"
      label="Date & Time"
      placeholder="Please Select..."
      inputStyle="box"
      labelStyle="stacked"
    />
    <MbscDatepicker
      :controls="['calendar', 'timegrid']"
      :selectMultiple="false"
      label="Date & Timegrid"
      placeholder="Please Select..."
      inputStyle="box"
      labelStyle="stacked"
    />
  </MbscPage>
</template>

// react-ts/src/demos/datetime/datetime/single-select/single-select.tsx
import React from 'react';
import { Datepicker, Page, setOptions /* localeImport */ } from '@mobiscroll/react';

setOptions({
  // localeJs,
  // themeJs
});

const App: React.FC = () => {
  return (
    <Page>
      <Datepicker
        controls={['date']}
        selectMultiple={false}
        inputOptions={{
          label: 'Date',
          inputStyle: 'box',
          labelStyle: 'stacked',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['time']}
        selectMultiple={false}
        inputOptions={{
          label: 'Time',
          inputStyle: 'box',
          labelStyle: 'stacked',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['timegrid']}
        selectMultiple={false}
        inputOptions={{
          label: 'Time grid',
          inputStyle: 'box',
          labelStyle: 'stacked',
          placeholder: 'Please Select...',
        }}
      />
      <Datepicker
        controls={['date', 'time']}
        selectMultiple={false}
        inputOptions={{
          label: 'Date & time',
          inputStyle: 'box',
          labelStyle: 'stacked',
          placeholder: 'Please Select...',
        }}
      />
    </Page>
  );
};
export default App;
