// mobiscroll-demos-angular/src/demos/datepicker/calendar/multiple-months/multiple-months.ts
import { Component } from '@angular/core';
import { setOptions /* localeImport */ } from '@mobiscroll/angular';

setOptions({
  // locale,
  // theme
});

@Component({
  selector: 'app-calendar-multiple-months',
  templateUrl: './multiple-months.html',
  standalone: false,
})
export class AppComponent {}

// vue/src/demos/calendar/calendar/multiple-months/multiple-months.vue
<script setup>
import { MbscDatepicker, setOptions /* localeImport */ } from '@mobiscroll/vue'

setOptions({
  // locale,
  // theme
})
</script>

<template>
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" :pages="1" />
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" :pages="2" />
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" :pages="3" />
  <MbscDatepicker :controls="['calendar']" display="inline" calendarType="month" pages="auto" />
</template>
